ha_mroonga.cpp, mysql-test/mroonga/storage/create/table/normalizer/primary_key/r/table_comment_with_using_hash.result, mysql-test/mroonga/storage/create/table/normalizer/primary_key/t/table_comment_with_using_hash.test
``USING HASH``でハッシュキーのテーブルを作る場合にも、テーブルコメントを使ったノーマライザーなどを変更する方法が使いたいです。
ご検討ください。
=> Support specifying options by table comment when primary key is using hash

ha_mroonga.cpp, mysql-test/mroonga/storage/fulltext/boolean_mode/pragma/default_operator/plus/r/with_astarisk.result, mysql-test/mroonga/storage/fulltext/boolean_mode/pragma/default_operator/plus/t/with_astarisk.test
そのときのメモリの状況にもよるかもしれませんが、プラグマを使って*でおわるような場合、うまく検索できないことがあります。
プラグマが含まれているときのクエリの長さが2バイト多いような気がしましたので修正しました。
ご検討ください。
=> Fix wrong keyword length when query include pragma

packages/rpm/centos/mysql57-community-mroonga.spec.in
This is patch for #77 
- Login and update password using same password string.
Because of autogenerated password is expired by default.
- INSTALL PLUGIN using autogenerated password.
- Expire password for resetting to fresh installed environment.
=> Fix mysql57-community-mroonga's installation issue.

packages/rpm/centos/mariadb-mroonga.spec.in
In current version of `mariadb-mroonga.spec`, there is no both stdout and stderr output redirection to /dev/null when running mysql to determine if -p option is needed. Therefore if root account is password protected, the install script prints `ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)`. This kind of error message makes users a bit confusing and to think the installation was unsuccessful even though `Enter password:` prompt follows.
One more thing which didn't patch in this PR is that in the install script, it seems it checks mroonga version (through mysql command) without any password option specified even if `$password_option` is set. This also seems need to be fixed.
=> Omit error messages when checking whether root is password protected or not

data/uninstall.sql, ha_mroonga.def, mysql-test/mroonga/include/mroonga/unload_mroonga_functions.inc, mysql-test/mroonga/storage/function/normalize/r/defaul.result, mysql-test/mroonga/storage/function/normalize/r/normalizer.result, mysql-test/mroonga/storage/function/normalize/r/record.result, mysql-test/mroonga/storage/function/normalize/t/default.test, mysql-test/mroonga/storage/function/normalize/t/normalizer.test, mysql-test/mroonga/storage/function/normalize/t/record.test, udf/mrn_udf_normalize.cpp, udf/sources.am
I want to use custom Normalizer of Groonga even if I don't use fulltext index.
So I've implemented mroonga_normalize function as UDF.
```
mroonga_normalize(string, [normalizer_name])
```
```sql
mysql> SELECT mroonga_normalize('aBcＡｂＣ㍑');
+--------------------------------------+
| mroonga_normalize('aBcＡｂＣ㍑') |
+--------------------------------------+
| abcabcリットル                   |
+--------------------------------------+
1 row in set (0.00 sec)
```
It is using NormalizerAuto as default.
And it can be specified any normalizer name as option.
Could you please check and merge it?
=> Add a new UDF mroonga_normalize()

ha_mroonga.cpp, mysql-test/mroonga/storage/fulltext/boolean_mode/pragma/syntax_script/r/operator.result, mysql-test/mroonga/storage/fulltext/boolean_mode/pragma/syntax_script/r/selector.result, mysql-test/mroonga/storage/fulltext/boolean_mode/pragma/syntax_script/t/operator.test, mysql-test/mroonga/storage/fulltext/boolean_mode/pragma/syntax_script/t/selector.test
I want to use  [Script syntax](http://groonga.org/docs/reference/grn_expr/script_syntax.html) by specifying ``*SS`` pragma.
The following is example for using [prefix_rk_search](http://groonga.org/docs/reference/functions/prefix_rk_search.html).
```sql
CREATE TABLE readings (
reading VARCHAR(255) PRIMARY KEY
) DEFAULT CHARSET=utf8
COLLATE=utf8_bin
COMMENT='default_tokenizer "TokenDelimit"';
CREATE TABLE items (
name VARCHAR(255) PRIMARY KEY,
readings TEXT COMMENT 'flags "COLUMN_VECTOR", type "readings"',
FULLTEXT INDEX items_index(readings) COMMENT 'table "readings"'
) DEFAULT CHARSET=utf8;
INSERT INTO items VALUES("日本", "ニホン ニッポン");
INSERT INTO items VALUES("ローマ字", "ローマジ");
INSERT INTO items VALUES("漢字", "カンジ");
SELECT *,
MATCH(readings)
AGAINST("*SS sub_filter(readings, …
```
=> Support Syntax Script pragma

mrn_table.cpp
Mroonga 5.04 introduced new keyword to specify a tokeninzer on Full Text Index.
http://mroonga.org/ja/docs/news.html#release-5-04
Release note says "parser" keyword had been deprecated and able to use until Mroonga 6.X.X.
Do you mean "parser" keyword will be removed in Mroonga 7.00?
(I seem "default_parser" had been already removed.)
The patch to add warning when using "parser" keyword.
This behaves like following.
```
mysql56> create table t4 (num serial, val varchar(32), FULLTEXT KEY (val) Comment 'parser "TokenBigram"') Engine Mroonga;
Query OK, 0 rows affected, 1 warning (0.06 sec)
mysql56> show warnings;
+---------+------+----------------------------------------------------------------------------------------------+
| Level   | Code | Message …
```
=> Add warning about deprecated using keyword "parser"

doc/source/developer/release.rst
We should use Visual Studio 12(2013) instead of Visual Studio 10(2010) in documents!
=> doc developer release: Use Visual Studio 12(2013) in building instruction in Windows

CMakeLists.txt
It seems there isn't link to libgroonga.so when mroonga is bundled and libgroonga isn't bundled.
Maybe you are not providing this case but I want to bundle mroonga to MySQL without libgroonga for my purpose.
=> cmake: add missing link to libgroonga  when mroonga is bundled and libgroonga isn't bundled

ha_mroonga.cpp, ha_mroonga.hpp, mysql-test/mroonga/storage/create/table/index/flags/r/index_medium.result, mysql-test/mroonga/storage/create/table/index/flags/r/index_small.result, mysql-test/mroonga/storage/create/table/index/flags/t/index_medium.test, mysql-test/mroonga/storage/create/table/index/flags/t/index_small.test
I would like to use ``GRN_OBJ_INDEX_MEDIUM`` flags on Mroonga to optimize memory usage for index of int column.
=> Support INDEX_MEDIUM/INDEX_SMALL

ha_mroonga.cpp
When indexes are broken, there is a case that the value of matched_record_keys or
info->result is equal to null.
This commit checks these value not to cause unexpected SEGV.
=> add missing null check

doc/source/developer/release.rst
To build Mroonga with Visual Studio 2015, it needs to install CMake 3.1 or later.
To build Mroonga with Visual Studio 2017, it needs to install CMake 3.9 or later.
My PowerShell script depends on newly `Invoke-Webrequest` Cmdlet which had been introduced in PowerShell 3.0 or later. (But PowerShell 2.0 is installed in Windows 7 by default.)
=> Fix build requirements for windows

doc/source/reference/server_variables.rst, ha_mroonga.cpp, lib/mrn_operations.cpp, lib/mrn_operations.hpp, mysql-test/mroonga/storage/variable/enable_operations_recording/r/insert.result, mysql-test/mroonga/storage/variable/enable_operations_recording/t/insert.test
I would like to disable recording operations for recovery because It takes a long time to rebuild the index in huge database case.
=> Add mroonga_operations_disable_recording variable

ha_mroonga.cpp, mysql-test/mroonga/include/mroonga/skip_mariadb_10_1_or_earlier.inc, mysql-test/mroonga/storage/column/generated/stored/t/add_column.test, mysql-test/mroonga/storage/column/generated/stored/t/delete.test, mysql-test/mroonga/storage/column/generated/stored/t/drop_column.test, mysql-test/mroonga/storage/column/generated/stored/t/insert.test, mysql-test/mroonga/storage/column/generated/stored/t/update.test, mysql-test/mroonga/wrapper/column/generated/stored/t/add_column.test, mysql-test/mroonga/wrapper/column/generated/stored/t/delete.test, mysql-test/mroonga/wrapper/column/generated/stored/t/drop_column.test, mysql-test/mroonga/wrapper/column/generated/stored/t/insert.test, mysql-test/mroonga/wrapper/column/generated/stored/t/update.test
#159 
supported virtual(computed) column of MariaDB.
Virtual(computed) columns starting with 5.2, 10.2.1
https://mariadb.com/kb/en/mariadb/virtual-computed-columns/
JSON functions starting with 10.2.3
https://mariadb.com/kb/en/mariadb/json-functions/
added JSON as an alias for TEXT with 10.2.7
https://jira.mariadb.org/browse/MDEV-9144
=> mariadb 10.2: support virtual column

packages/debian-mariadb-10.0/control.in
I get follwoing error on installing mroonga  debian package to minimal stretch environment.
```
Preparing to unpack .../mariadb-server-10.1-mroonga_7.06-1_amd64.deb ...
/var/lib/dpkg/tmp.ci/preinst: 1: /var/lib/dpkg/tmp.ci/preinst: lsb_release: not found
dpkg: error processing archive /var/cache/apt/archives/mariadb-server-10.1-mroonga_7.06-1_amd64.deb (--unpack):
subprocess new pre-installation script returned error exit status 127
/var/lib/dpkg/tmp.ci/postrm: 1: /var/lib/dpkg/tmp.ci/postrm: lsb_release: not found
dpkg: error while cleaning up:
subprocess new post-removal script returned error exit status 127
Errors were encountered while processing:
/var/cache/apt/archives/mariadb-server-10.1-mroonga_7.06-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
The packge …
=> deb: Error on preinst and postrm (missing depends to lsb-release )

lib/mrn_count_skip_checker.cpp, mysql-test/mroonga/storage/optimization/count_skip/full_text_index/r/multi_column_index.result, mysql-test/mroonga/storage/optimization/count_skip/full_text_index/t/multi_column_index.test
Mroonga has [a feature](http://mroonga.org/docs/reference/optimizations.html#row-count) to skip the data retrieval routine when the MySQL/MariaDB server has no interest on the actual row records.
This patch enables the optimimization for a multi-column fulltext index query like this:
```sql
SELECT COUNT(*) FROM tbl WHERE MATCH (col1, col2) AGAINST ('q');
```
In essence, this patch eliminates the following `if` conditional in CountSkipChecker:
```cpp
if (select_lex_->select_n_where_fields == 1) {
... // Enable optimization
} else {
... // Disable optimization
}
```
The observation behind this modification is that this conditional is somewhat meaningless, because, at this point in the code path, the query being executed is guaranteeed to:
* be not a nested query.
* select no field (column) …
=> Enable "count-skip" optimization for multi-column fulltext search

ha_mroonga.cpp, mrn_mysql_compat.h
Since MySQL 8.0.13, field_name of key_part_spec must be accessed by
get_field_name().
TODO: fix can_switch_engines() which is also removed from MySQL 8.0.13
=> mysql8 storage: don't access field name directly in key_part_spec

appveyor.yml
MariaDB search symbols from same directory with plugin.
MariaDB 10.1: pdb is installed to lib/plugin/ha_mroonga.pdb
MariaDB 10.2/10.3: pdb is installed to symbols/ha_mroonga.pdb
=> appveyor: put Mroonga pdb in same directory with plugin

tools/travis/script.sh
When MROONGA_RELEASE_REQUIREMENT=yes is enabled, at least, minimum
test case must be passed.
=> mysql8.0 test: split into build and test jobs

packages/windows/install-mroonga.ps1
In the previous versions, it requires to update install-mroonga.ps1
for each teeny release, so it is fixed for 10.4.*.
=> appveyor: run mysql_install_db for MariaDB 10.4.

mysql-test/mroonga/storage/index/multiple_column/select/t/varchar.test
Warnings:
Warning	1280	Name 'property' ignored for PRIMARY key.
=> test: suppress warning since 10.3.18/10.4.8

tools/travis/before_script.sh
It causes CMAKE configuration error because of failing to detect
installed OpenSSL library on that system
--
Wrong option or path for
WITH_SSL=/export/home/pb2/build/sb_0-36131509-1569568392.28/dep2.
Make sure you have specified a supported SSL version.
Valid options are :
system (use the OS openssl library),
yes (synonym for system),
</path/to/custom/openssl/installation>
CMake Error at cmake/ssl.cmake:66 (MESSAGE):
Please install the appropriate openssl developer package.
Call Stack (most recent call first):
cmake/ssl.cmake:265 (FATAL_SSL_NOT_FOUND_ERROR)
CMakeLists.txt:573 (MYSQL_CHECK_SSL)
-- Configuring incomplete, errors occurred!
=> travis: remove hardcoded DWITH_SSL option

.travis.yml
Because the latest source package for Percona Server 5.7 was prepared.
TravisCI result for Percona Server5.7 has been sucess.
https://travis-ci.org/github/komainu8/mroonga/jobs/667043501
=> travis percona: enable Percona Server 5.7

tools/travis/before_script.sh
Because frequent downloads from CI kills the Boost official site bandwidth allowance.
And https://bugs.mysql.com/bug.php?id=96266 has already fixed.
=> travis ci: modify download destination for the Boost library

doc/locale/ja/LC_MESSAGES/install.po, doc/source/conf.py, doc/source/install/windows.rst
Because We often forget to update the link,
if we make links that specify the version of MariaDB.
=> doc: use release page instead of direct download links for Windows packages

packages/mysql-server-8.0-mroonga/yum/mysql80-community-mroonga.spec.in
Because if we make MySQL8, run out of disk space for GitHub Actions
=> rpm centos: remove a needless procedure

packages/mysql-server-5.7-mroonga/debian/control.in
Because if libncurses5-dev is missing, MySQL in Ubuntu 16.04 occurs the following build error.
```
CMake Error at cmake/readline.cmake:71 (MESSAGE):
Curses library not found.  Please install appropriate package,
remove CMakeCache.txt and rerun cmake.On Debian/Ubuntu, package name is libncurses5-dev, on Redhat and derivates it is ncurses-devel.
Call Stack (most recent call first):
cmake/readline.cmake:100 (FIND_CURSES)
cmake/readline.cmake:193 (MYSQL_USE_BUNDLED_EDITLINE)
CMakeLists.txt:581 (MYSQL_CHECK_EDITLINE)
```
See more details: [build log](https://launchpadlibrarian.net/479172238/buildlog_ubuntu-xenial-i386.mysql-server-5.7-mroonga_10.02-1.ubuntu16.04.2_BUILDING.txt.gz)
=> packages: add a missing dependency package for Ubuntu 16.04

packages/mysql-server-5.7-mroonga/Rakefile
It reached EOL on on January 23 2020.
=> packages: drop Ubuntu 19.04

packages/mariadb-server-10.3-mroonga/Rakefile
I confirming whether we can build packages for Ubuntu 20.04.
And this modify needs 6e1bc71562f81886b2e556c4f99e62b7ca9beedd.
=> packages mariadb-server-10.3: add support for Ubuntu 20.04(Focal Fossa)

appveyor.yml
The bison package for pacman is compressed with the ZST algorithm from 3.6.2-1.
However, pacman can't handle that unless we first install zstd.
=> appveyor: install zstd before bison packages

appveyor.yml
Because MariaDB 10.1 will be EOL soon.
=> appveyor: drop MariaDB 10.1

doc/locale/ja/LC_MESSAGES/install.po, doc/source/install/ubuntu.rst, packages/mariadb-server-10.3-mroonga/Rakefile
It reached EOL on July 17 2020.
See: https://wiki.ubuntu.com/Releases
=> packages: drop Ubuntu 19.10

ha_mroonga.cpp, ha_mroonga.hpp
GitHub: fix GH-333 Reported by tomop-tg.
We use ha_drop_table instead of ha_delete_table.
Because ha_delete_table is deleted since mariadb-server 10.5.5
by below commit.
https://github.com/MariaDB/server/commit/c55c292832e2776d37e06c43174ac006e00143a2
=> Add support for mariadb-server 10.5.5

mysql-test/mroonga/storage/index/multiple_column/unique/t/decimal.test
Because the format of the error message in mariadb-server was modified by below commit.
https://github.com/MariaDB/server/commit/cb4da5da74b7a6f2e7c4f4ed1b0e5affe45fe2a2
However, the format of it is not modified in MySQL, PerconaServer, and MariaDB 10.1.
Therefore, we separated `mroonga/storage/index/multiple_column/unique/{t, r}/decimal.{test, result}`.
=> test: follow error message change in mariadb-10.5.3, 10.4.13, 10.3.23, and 10.2.32

appveyor.yml, packages/source/patches/mariadb-10.5.5-add-a-missing-export-symbol.diff
This patch resolves link error for packages for MariaDB10.5.5 of the Windows version.
We need to export the symbol of `type_handler_enum`. Because `type_handler_enum` is not defined in a header file.
Probably, this is a bug for MariaDB 10.5.5. Therefore, we will send a patch to upstream.
If the bug will be fixed in upstream, we will delete this patch.
=> appveyor: add a patch for fixing link error

doc/source/developer.rst
Because this contents already moved to developer/release.
=> doc developer: remove a explanation about release

.github/workflows/windows.yml
Because Invoke-WebRequest does not support HTTP status 302.
=> ci windows: use curl instead of Invoke-WebRequest

doc/locale/ja/LC_MESSAGES/news.po
v10.9-Percona Serverの対応バージョンの記述が正しくなかったようなので修正.
=> doc news: fix percona server version

packages/percona-server-8.0-mroonga/yum/percona-server-80-mroonga.spec.in
Because CentOS 8 ships zlib 1.2.11.
=> packages percona-server-8.0: use the bundled zlib only on CentOS 7

.github/workflows/windows.yml
Because if we don't use an archive for uploading an artifact, an
artifact uploading becomes slow.
=> packages windows: Use an archive for uploading an artifact

packages/mariadb-server-10.2-mroonga/yum/centos-7/Dockerfile, packages/mariadb-server-10.3-mroonga/yum/centos-7/Dockerfile, packages/mariadb-server-10.4-mroonga/yum/centos-7/Dockerfile, packages/mariadb-server-10.5-mroonga/yum/centos-7/Dockerfile, packages/mysql-server-5.6-mroonga/yum/centos-7/Dockerfile, packages/mysql-server-5.7-mroonga/yum/centos-7/Dockerfile, packages/mysql-server-8.0-mroonga/yum/centos-7/Dockerfile, packages/percona-server-5.6-mroonga/yum/centos-7/Dockerfile, packages/percona-server-5.7-mroonga/yum/centos-7/Dockerfile, packages/percona-server-8.0-mroonga/yum/centos-7/Dockerfile
Because libgroonga 10.1.1 depends on libarrow 2.0.0.
However, currently the repository of Apache Arrow on CentOS7 provide
libarrow 3.0.0.
Therefore, we can't build Mroonga on CentOS7 now.
(e.g. https://github.com/mroonga/mroonga/runs/1767521129?check_suite_focus=true#step:12:1368)
This patch is temporary modification until release Groonga 11.0.0.
=> packages centos-7: use the old Apache Arrow

configure.ac, packages/mysql-server-8.0-mroonga/yum/centos-7/Dockerfile, packages/mysql-server-8.0-mroonga/yum/mysql80-community-mroonga.spec.in
1. mysql-server use the "crc32_z" function since version 8.0.23. This function is included zlib library, since version 1.2.9.
If the version of zlib library is old that is provided on our OS (e.g. CentOS7), we can't build Mroonga.
2. mysql-server use the "z_size_t" type. This type is included "zconf.h".
However, "zconf.h" does not exist in MySQL source directory.
This header is generated in MySQL build directory after build MySQL.
Therefore, we use the zlib library that is bundled MySQL 8.
=> packages mysql-server-8.0: use bundled zlib on centos7

.github/workflows/package.yml
GitHub actions has updated the OS version to Ubuntu 20.0.4 lately.
libmysqld-dev is obsolete in Ubuntu 20.0.4 LTS.
Therefore, we use libmysqlclient-dev instead of it for `/usr/bin/mysql_config`.
=> github-actions: use libmysqlclient-dev for /usr/bin/mysql_config

ha_mroonga.cpp, lib/mrn_debug_column_access.cpp, lib/mrn_debug_column_access.hpp, mrn_mysql_compat.h
Because the following patch changes function prototypes for "dbug_tmp_restore_column_maps" and "dbug_tmp_use_all_columns".
See: https://github.com/MariaDB/server/commit/21809f9a450df1bc44cef36377f96b516ac4a9ae
=> Don't use raw bitmap

packages/mroonga-package-task.rb
Mroonga's package name is changed  by the following commit.
https://github.com/mroonga/mroonga/commit/6bd846f2136fd7c657f232212cfc4759f9dc7e59
However, Ubuntu's MySQL package is mariadb-server-10.x and mysql-server-5.x.
Therefore, we need to convert Mroonga's package name to Ubuntu's package name.
Otherwise, we can't get version for MySQL and MariaDB for Ubuntu.
=> package ubuntu: package name change to ubuntu's package name

packages/percona-server-8.0-mroonga/yum/percona-server-8.0-mroonga.spec.in
Because CentOS 8 has not cmake3.
=> Use cmake on CentOS 8

.github/workflows/linux.yml, packages/mariadb-10.3-mroonga/debian/changelog
We need to increase minor version of Debian package for Mroonga when we update Debian package for Mroonga.
=> package mariadb-10.3: rebuild against the latest MariaDB 10.3 package

.github/workflows/linux.yml
Because we will rename maintenance branch name to "maintenance/XX.XX" from "vXX.XX-maintenance".
=> ci: add support for "maintenance/XX.XX" branch name

packages/mariadb-10.3-mroonga/yum/centos-8/Dockerfile, packages/mariadb-10.4-mroonga/yum/centos-8/Dockerfile
Because forced jemalloc to be used by
https://github.com/MariaDB/server/commit/e1bf1aea5cd8f8b5a1b15fd2a8ca0b8205654431
However, MariaDB 10.5 doesn't apply this modification.
Because it doesn't use jemalloc.
See: https://github.com/MariaDB/server/commit/9bbedcdd590f2c25c79bd9f367a7f54c1fcefdcb
=> packages mariadb: add a missing dependency package

.github/workflows/windows.yml
The download URL for FTP of PCRE2 can't use.
See: https://www.pcre.org/
Therefore, we need to use the URL of GitHub to download PCRE2 source code.
The cause of this problem is in MariaDB 10.5 or later.
We will remove this patch when this problem is resolved in MariaDB.
This problem has already been resolved at MariaDB/server@8d7196c
Therefore, this problem will resolve in the next release of MariaDB.
=> packages windows: add a patch for fixing build of Windows on CI

.github/workflows/linux.yml, packages/mroonga-package-task.rb
We use this feature when MySQL, MariaDB, or Percona Server are
upped after the release of Mroonga.
Usage:
cd mroonga/packages/mariadb-10.3-mroonga/
rake apt BRANCH="maintenance/11.08" GITHUB_ACCESS_TOKEN=...
=> package: add support for updating package

.github/workflows/install.yml
Because vms id of Vagrantfile is changed at 7831130adaeb596e7946cb468d8700486f868d6f.
=> ci: use code name

.github/workflows/linux.yml, packages/mariadb-10.3-mroonga/yum/almalinux-8/Dockerfile, packages/mariadb-10.4-mroonga/yum/almalinux-8/Dockerfile, packages/mariadb-10.5-mroonga/yum/almalinux-8/Dockerfile, packages/mariadb-10.6-mroonga/yum/almalinux-8/Dockerfile, packages/mysql-community-8.0-mroonga/yum/almalinux-8/Dockerfile, packages/mysql-community-8.0-mroonga/yum/centos-8/Dockerfile, packages/mysql-community-8.0-mroonga/yum/mysql-community-8.0-mroonga.spec.in, packages/yum/test.sh
Because groonga-normalizer-mysql for AlmaLinux 8 has been already released.
=> ci: enable almalinux 8

.github/workflows/install.yml
Because Ubuntu Impish has been already available on bento.
=> ci install: enable Ubuntu 21.10 (Impish)

packages/mysql-community-5.7-mroonga/apt/debian-buster/Dockerfile, packages/mysql-community-5.7-mroonga/yum/centos-7/Dockerfile, packages/mysql-community-8.0-mroonga/apt/debian-bullseye/Dockerfile, packages/mysql-community-8.0-mroonga/apt/debian-buster/Dockerfile
Because the official MySQL YUM repository and MySQL APT repository updated public key for showing the validity of packages in these repositories.
In addition, mysql57-community-release-el7.rpm is already not being maintained in https://repo.mysql.com/.
Because mysql57-community-release-el7.rpm is not updated since 2017-4-27.
Therefore, we use mysql80-community-release-el7.rpm instead of mysql57-community-release-el7.rpm.
mysql80-community-release-el7.rpm includes information of mysql57-community-release-el7.rpm .
See: https://dev.mysql.com/doc/refman/8.0/en/linux-installation-yum-repo.html#yum-repo-select-series
However, if we use mysql80-community-release-el7.rpm, we need to select a release series by yum-config-manager.
=> packages: use the latest mysql-apt-config

packages/apt/test.sh, packages/yum/test.sh
Because the official MySQL YUM repository and MySQL APT repository
updated public key for showing the validity of packages in these
repositories.
In addition, mysql57-community-release-el7.rpm is already not being
maintained in https://repo.mysql.com/.
Because mysql57-community-release-el7.rpm is not updated since
2017-4-27.
Therefore, we use mysql80-community-release-el7.rpm instead of
mysql57-community-release-el7.rpm.
mysql80-community-release-el7.rpm includes information of
mysql57-community-release-el7.rpm .
See: https://dev.mysql.com/doc/refman/8.0/en/linux-installation-yum-repo.html#yum-repo-select-series
However, if we use mysql80-community-release-el7.rpm, we need to
select a release series by yum-config-manager.
=> mysql test: update the packages that set the repository of MySQL

mysql-test/mroonga/include/mroonga/check_version.inc, mysql-test/mroonga/include/mroonga/have_mariadb_10_5_14_or_later.inc, mysql-test/mroonga/include/mroonga/skip_mariadb_10_5_14_or_later.inc, mysql-test/mroonga/storage/alter_table/add_index/unique/mariadb_10_5_14_or_later/multiple_column/r/duplicated.result, mysql-test/mroonga/storage/alter_table/add_index/unique/mariadb_10_5_14_or_later/multiple_column/t/duplicated.test, mysql-test/mroonga/storage/alter_table/add_index/unique/mariadb_10_5_14_or_later/r/duplicated.result, mysql-test/mroonga/storage/alter_table/add_index/unique/mariadb_10_5_14_or_later/t/duplicated.test, mysql-test/mroonga/storage/alter_table/add_index/unique/multiple_column/t/duplicated.test
Because the error code is changed since MariaDB 10.5.14 or later.
In addition, this error case occurs "ER_DUP_ENTRY" on InnoDB.
Therefore, Mroonga occurs "ER_DUP_ENTRY" in this error case according to InnoDB's behavior.
=> test: use ER_DUP_ENTRY instead of ER_DUP_UNIQUE

packages/yum/test.sh
Because we have already been released Mroonga 12.02 for Amazon Linux 2.
=> packages yum test: enable upgrade test for Amazon Linux 2

.gitignore, CMakeLists.txt, configure.ac, data/Makefile.am, data/deb/postinst.sh, data/install.sql.in, data/install_plugin.sql.in, data/rpm/post.sh
This is testing now.
GitHub: fix #509 Reported by Jérome Perrin. Thanks!!!
=> package: don't require to run update.sql when the execution install.sql

.github/workflows/linux.yml, Vagrantfile, packages/apt/test.sh
Because Ubuntu Jammy has already available on bento.
=> ci linux: enable "Test" for Ubuntu Jammy

doc/source/developer/release.rst
`--watch` is needless because it's enabled by default.
=> doc release: Remove needless --watch option

doc/source/developer/release.rst
Remove `DOCUMENT_VERSION` and `DOCUMENT_VERSION_FULL` from `make update-document` because they are automatically specified.
=> doc: Remove needless variables from update-document

packages/mariadb-10.5-mroonga/debian/changelog
We can marge this PR when this PR pass all CI.
=> package mariadb-10.5 bullseye: rebuild against the latest MariaDB 10.5 package

packages/yum/test.sh
Because we released Mroonga 12.10.
=> yum test: enable upgrade test for MariaDB 10.10

.github/workflows/linux.yml
Because Currently we can't build the RPM of Percona-Server from SPEC. Probabry the cause of this problem by Percna Server.
See: https://jira.percona.com/browse/PS-8623
We can't build of packages for Percona Server until resolved this problem.
=> packages percona-server: disable build of packages for Percona Server

.github/workflows/linux.yml
Because the library to need build the RPM package of Percona Server already has been able to aveirable for download.
=> packages percona-server: enable build of packages for Percona Server

.github/workflows/linux.yml
Because Ubuntu jammy has already provided MySQL community server 8.0.
=> ci: enable build for Mroonga with MySQL community 8.0 on Ubuntu jammy

mrn_mysql_compat.h
GitHub: fix GH-605 
Error compiling the Mroonga plugin 13.00 with MariaDB 10.11.2 in Debian 11.6.
=> Add support for building with MariaDB 10.11.2

.github/workflows/linux.yml, packages/apt/test.sh
Because the mysql-apt-config's config script refers the DEBIAN_FRONTEND environment variable directly.
It doesn't refer the debconf setting.
=> ci : Sepcify "DEBIAN_FRONTEND=noninteractive" when we install or upgrade "mysql-apt-config"

packages/percona-server-8.0-mroonga/yum/almalinux-8/Dockerfile
* Use GCC 12
Because MySQL 8.0.33 use GCC 12 instead of GCC 11.
See:
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-33.html
=>  packages percona-server-8.0: add support for MySQL 8.0.33

.github/workflows/install.yml
=> ci install: use LXD instead of Vagrant

.github/workflows/linux.yml, packages/apt/test.sh, packages/yum/test.sh
Because Vagrant isn't OSS.
We use LXC on Ubuntu 20.04 in test of Mroonga packages for Linux.
Because CentOS 7 requires CGroupV1.
If we use LXC on Ubuntu 22.04, CentOS 7 image can not start.
Because LXC on Ubuntu 22.04 use CGroupV2 normally.
=> ci linux: use LXD instead of Vagrant

.github/workflows/windows.yml
We can show Groonga revision by using `actions/checkout`.
We can't use parent directory with `actions/checkout`. So we need to change directory structure:
Before:
```text
$PWD: Mroonga source
$PWD/../source: MariaDB with Mroonga/Groonga/groonga-normalizer-mysql
$PWD/../build: Build directory
$PWD/../install: Install destination
```
After:
```text
$PWD/mariadb: MariaDB with Mroonga/Groonga/groonga-normalizer-mysql
$PWD/build: Build directory
$PWD/install: Install destination
```
=> ci windows: display Groonga revision

data/rpm/post.sh, data/rpm/preun.sh, packages/yum/test.sh
Because LXD images of Almalinux 8,9 and CentOS 7 have not "which" command in default.
=> rpm: don't use "which" command

packages/mysql-community-8.0-mroonga/yum/almalinux-8/Dockerfile, packages/mysql-community-8.0-mroonga/yum/almalinux-9/Dockerfile
Because GPG keys of MYSQL's YUM repository were updated.
This PR resolve GPG check error when we install mysql-community-devel packages as below.
https://github.com/mroonga/mroonga/actions/runs/7577804071/job/20639333567#step:9:7064
I think if we resolve the above error, CI for Mroonga with MySQL Community 8.0 fail yet.
Because  the new version of MySQL Community 8.0 had been released.
So, I will fix it in the other PR after we merge this PR.
=> packages mysql-community-8.0: use the latest settings of MySQL's YUM repository

packages/percona-server-8.0-mroonga/yum/percona-server-8.0-mroonga.spec.in
Because Percona Server for MySQL 8.0.35-27( https://docs.percona.com/percona-server/8.0/release-notes/8.0.35-27.html ) had been released.
This PR resolve "error: Failed build dependencies:" when we install "percona-server-8.0-mroonga" as below.
* https://github.com/mroonga/mroonga/actions/runs/7577804071/job/20639334523#step:9:3220
* https://github.com/mroonga/mroonga/actions/runs/7577804071/job/20639334696#step:9:4046
* https://github.com/mroonga/mroonga/actions/runs/7577804071/job/20639334830#step:9:3944
=> packages percona-server-8.0: use the latest Percona Server

packages/mysql-community-8.0-mroonga/apt/debian-bookworm/Dockerfile, packages/mysql-community-8.0-mroonga/apt/debian-bullseye/Dockerfile, packages/mysql-community-8.0-mroonga/apt/ubuntu-jammy/Dockerfile, packages/mysql-community-8.0-mroonga/yum/centos-7/Dockerfile
These modifications same as #663.
I forgot modification for CentOS7, Debian bullseye, Debian bookworm, and Ubuntu jammy.
=> packages mysql-community-8.0: use the latest settings of MySQL's repositories for CentOS7, Debian bullseye, Debian bookworm, and Ubuntu jammy

packages/mysql-community-8.0-mroonga/yum/mysql-community-8.0-mroonga.spec.in, packages/mysql-community-minimal-8.0-mroonga/yum/mysql-community-minimal-8.0-mroonga.spec.in
Because MySQL 8.0.36( https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-36.html ) had been released.
This PR resolve "error: Failed build dependencies:" when we install "mysql-community-minimal-8.0-mroonga" and "mysql-community-8.0-mroonga".
=> packages mysql-community-8.0: use the latest MySQL Community Server

packages/mariadb-10.11-mroonga/yum/mariadb-10.11-mroonga.spec.in, packages/mariadb-10.4-mroonga/yum/mariadb-10.4-mroonga.spec.in, packages/mariadb-10.5-mroonga/yum/mariadb-10.5-mroonga.spec.in, packages/mariadb-10.6-mroonga/yum/mariadb-10.6-mroonga.spec.in
Because MariaDB released new version.
See: https://mariadb.org/mariadb/all-releases/
This PR only fix failure of build Mroonga with MariaDB.
So, tests for Mroonga still fail even if this PR merge.
=> packages mariadb: bump MariaDB version

packages/yum/test.sh
mysql80-community-release-el${major_version}.rpm is latest settings of YUM repository.
So, we don't need to specify release number such as mysql80-community-release-el8-3.noarch.rpm.
=> test mysql-community-8.0: use the latest settings of MySQL's YUM repository

ha_mroonga.hpp
Because HA_EXTRA_IGNORE_INSERT was removed in MariaDB 10.6.16 or later and MariaDB 10.11.06 or later.
See: https://github.com/MariaDB/server/commit/c438284863db2ccba8a04437c941a5c8a2d9225b
=> mariadb: unuse HA_EXTRA_IGNORE_INSERT

mrn_mysql_compat.h
This API change enabled in all mariadb that we support currently. So, we can add "my_" prefix if build target is mariadb. a limit is not need by mariadb version.
See: https://github.com/MariaDB/server/commit/273078c5faa19b60e2cc93330d18534fae221487
=> mariadb10.5 10.6: follow bitmap_init() and bitmap_free() API change

ha_mroonga.cpp, mrn_mysql_compat.h
`my_bitmap_init()` doesn't have the fourth argument (`thread_safe`) since MariaDB 10.7 or later.
However, `my_bitmap_init()` has the fourth argument in MariaDB 10.5 and 10.6.
The following change exists in MariaDB 10.7 or later.
See: https://github.com/MariaDB/server/commit/0299ec29d4af3230741a62d5443c0562269b05b2
=> mariadb 10.5 10.6: add a missing argument for my_bitmap_init()

packages/mysql-community-minimal-8.0-mroonga/yum/almalinux-8/Dockerfile
TODO: Test
If we install mysql-community-release after mysql-community-minimal-release, we can't install mysql-community-minimal-release.
Because mysql-community-minimal-release and mysql80-community-release are conflicting. 
See: https://github.com/mroonga/mroonga/actions/runs/9265261501/job/25487027793#step:9:5291
However, if we install mysql-community-release firstly, we can replace mysql80-community-release to mysql-community-minimal-release.
Currently, We install mysql-community-release only to install mysql-community-devel in this job. So, no problem that mysql-community-release replace to mysql-community-minimal-release, anytime after we install mysql-community-devel.
=> packages mysql-community-minimal-8.0: install mysql-community-release before mysql-community-minimal-release

packages/apt/test.sh
Currently, we couldn't be verified signatures of 'http://repo.mysql.com/apt/debian bookworm InRelease' as below.
https://github.com/mroonga/mroonga/actions/runs/9309443050/job/25625429475#step:6:781
Because we use old public key.
=> ci test: use the latest mysql-apt-config

.github/workflows/install.yml
close: https://github.com/mroonga/mroonga/issues/690
The reasons for this change are as follows.
- Using both LXD and Incus increases maintenance costs.
- Standardizing on Incus will simplify our infrastructure and reduce these costs.
=> ci install: migrate LXD to Incus

packages/mysql-8.0-mroonga/apt/ubuntu-noble/Dockerfile
It seems that groonga-apt-source-latest-${codename}.deb is not used after we get this file by wget.
=> packages mysql-8.0: remove a unuse file

Rakefile
We will drop support for GNU Autotools. This is a part of the work.
We can use `rake release:version:update` instead of `make update-latest-release`.
We don't need to implement the `update-latest-release.rb` part:
https://github.com/mroonga/mroonga/blob/72121be89dff15665490b8669de441bd12113ecf/Makefile.am#L68-L74
Because:
* There are no information updated by it in `doc/source/install/*.rst` and `doc/local/*/LC_MESSAGES/install.po`
* We can update `mroonga/mroonga.com`'s `_config.yml` separately.
=> Implement "make update-latest-release" by Rake

packages/apt/test.sh
Specifying package names and code names needs high maintenance costs.
Because we have to change it when new OS version is released every time.
=> ci linux: skip upgrade test if packages haven't been released

Rakefile
We will drop support for GNU Autotools. This is a part of the work.
We can use `rake dev:version:bump` instead of `make update-version`.
`rake dev:version:bump` modify the following files.
* plugin_version
* version_full
* version_major
* version_minor
* version_micro
Usage:
`rake dev:version:bump NEW_VERSION=xx.xx`
We must specify `NEW_VERSION` when we execute `rake dev:version:bump`.
=> Implement "make update-version" by Ruby

Rakefile
I forgot add writing target file in #698. I add it in this PR.
We must also modify `version_in_hex` when we execute `rake dev:version:bump`.
=> Add a missing write target file

doc/.gitignore, doc/Gemfile
ref: https://github.com/mroonga/mroonga/issues/695#issuecomment-2172734327
We faced the following error during generating documents.
Because we didn't install `gem gettext` so we couldn't require it.
```
<internal:/home/kodama/.rbenv/versions/3.3.2/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- gettext/tools (LoadError)
from <internal:/home/kodama/.rbenv/versions/3.3.2/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
from /home/kodama/work/cpp/mroonga/doc/../doc/update-edit-po.rb:20:in `<main>'
```
```console
$ cmake -S . -B ../mroonga.doc -GNinja \
-DMRN_WITH_DOC=ON \
-DCMAKE_INSTALL_PREFIX=/tmp/local \
-DMYSQL_SOURCE_DIR=~/work/cpp/mysql-8.4.0 \
-DMYSQL_BUILD_DIR=~/work/cpp/mysql-8.4.0.build \ …
```
=> doc: gem install `gettext` for generating documents

.github/workflows/linux.yml, packages/mysql-8.0-mroonga/apt/ubuntu-noble/Dockerfile, packages/mysql-8.0-mroonga/debian/control.in
We build Mroonga package for Ubuntu on Launchpad,
but "apt build-dep -y mysql-server" command is not used on Launchpad when we build Mroonga on Launchpad.
Only dependency packages that is specified Build-Depends of debian/control are installed on Launchpad.
Therefore, build of Mroonga package for Ubuntu failure on Launchpad even if build of Mroonga package for Ubuntu successful on CI.
So, we remove "apt build-dep -y mysql-server" from CI. We can notice missing dependency packages with CI by this PR.
I will apply same modification to Mroonga for Ubuntu jammy by the other PR.
=> packages mysql-8.0: don't use "apt build-dep" when Mroonga build for Ubuntu noble

CMakePresets.json
ref: https://github.com/mroonga/mroonga/issues/695
This change introduces a new preset in `CMakePresets.json` to simplify the process of generating documentation.
It allows both new and existing developers to quickly and easily produce documents.
```console
$ cmake -S . -B ../mroonga.doc --preset=doc \
-DCMAKE_INSTALL_PREFIX=/tmp/local \
-DMYSQL_SOURCE_DIR=~/work/cpp/mysql-8.4.0 \
-DMYSQL_BUILD_DIR=~/work/cpp/mysql-8.4.0.build \
-DMYSQL_CONFIG=/tmp/local/bin/mysql_config
$ cmake --build ../mroonga.doc
$ open ../mroonga.doc/doc/ja/html/index.html
```
Update how to generate documentation using `CMake` instead of `GNU Autotools`
- https://mroonga.org/docs/contribution/documentation.html 
- https://mroonga.org/docs/developer.html#adding-and-updating-documents
=> cmake: add a doc preset to CMakePresets for generating documentations

.github/workflows/linux.yml, packages/mysql-8.0-mroonga/apt/ubuntu-jammy/Dockerfile
This modification is the same kind of #701.
We remove "apt build-dep -y mysql-server" when we build Mroonga for Ubuntu jammy on CI. The reason for this modification refer #701.
=> packages mysql-8.0: don't use "apt build-dep" when Mroonga build for Ubuntu jammy

.github/workflows/linux.yml, packages/mariadb-10.11-mroonga/apt/ubuntu-noble/Dockerfile, packages/mariadb-10.11-mroonga/debian/control.in
This modification is the same kind of #701.
We remove "apt build-dep -y mysql-server" when we build Mroonga for Ubuntu jammy on CI. The reason for this modification refer #701.
Also, This modification resolve https://launchpadlibrarian.net/735682999/buildlog_ubuntu-noble-amd64.mariadb-10.11-mroonga_14.04-1.ubuntu24.04.1_BUILDING.txt.gz probably.
=> packages mariadb-10.11: don't use "apt build-dep" when Mroonga build for Ubuntu noble

Rakefile
We will drop support for GNU Autotools. This is a part of the work. We can use `rake release:tag` instead of `make tag`.
The behavior of this modification https://github.com/mroonga/mroonga/blob/v13.05/Makefile.am#L45-L47 about the same as below.
* Setting tag by `git tag vXX.XX -a -m "Mroonga XX.XX!!!"`
* Push tag to Mroonga repository by `git push origin "vXX.XX"`
Usage:
$ rake release:tag
=> Implement "make tag" by Ruby

packages/mroonga-package-task.rb
Upload script use "gh release upload #{tag_name}" when we upload source archive. The tag name of Mroonga is vXX.XX, but the tag name is XX.XX (missing "v") in upload script currently.
Therefore, "gh release upload #{tag_name}" is failed. Because tag name such as XX.XX does not exist.
=> packages: add a missing definition

CMakePresets.json
The following error raised.
Because we have to specify the `binaryDir` by version 2 and it is optional after version 3.
- ref: [See also `binaryDir`](https://cmake.org/cmake/help/v3.30/manual/cmake-presets.7.html#configure-preset)
```console
$ cmake --list-presets
CMake Error: Could not read presets from /host:
Preset "doc" missing field "binaryDir"
Invalid preset: "doc"
```
I think of the following options. And the I chose the second option. Because it will be better for developers to decide their own build directories and keep CMakePresets.json simple for maintenances.
1. Set `"binaryDir": xxx` and use `"version: 1"`.
2. Specify `"version: 3"` without setting `"binaryDir": xxx` (Upgrade the required CMake version).
=> cmake: update CMake presets' JSON schema version from 1 to 3

.github/workflows/windows.yml
The following error happened when uploading Windows' packages on release step.
ref: https://github.com/mroonga/mroonga/actions/runs/9575531620/job/26400564227
```
Run gh release upload ${Env:GITHUB_REF_NAME} `
gh release upload ${Env:GITHUB_REF_NAME} `
"${Env:ARTIFACT_NAME}.zip"
shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
env:
PACKAGE_PLATFORM: winx64
VC_ARCHITECTURE: x64
MARIADB_VERSION: 10.11.8
MROONGA_VERSION: 14.04
ARTIFACT_NAME: mariadb-10.11.8-with-mroonga-14.04-winx64
CMAKE_C_COMPILER_LAUNCHER: ccache
CMAKE_CXX_COMPILER_LAUNCHER: ccache
GITHUB_TOKEN: ***
failed to run git: fatal: not a git repository (or any of the parent directories): .git
Error: Process completed with exit code 1.
```
As the error said, there is no Git repository we can reference to detect …
=> ci windows: fix the uploading packages error by checking out source

.github/workflows/install.yml
Fix #720.
We confirmed successful install tests for Ubuntu 24.04 (noble) as below CI.
https://github.com/mroonga/mroonga/actions/runs/9608564664?pr=724
=> ci install: add support Ubuntu 24.04

packages/mariadb-10.6-mroonga/debian/rules
Fix #718.
MariaDB' source directory name is changed to mariadb-${mariadb_major_minor_micro} from mariadb-${mariadb_major_minor}-${mariadb_major_minor_micro} since MariaDB 10.6.18 on Ubuntu.
So, The build of Mroonga on Ubuntu is failure because of mariadb source directory is not found.
I modify source directory name correctly by this PR.
=> packages mariadb-10.6: fix wrong source base

.github/workflows/linux.yml
The SRPM of mysql-community-minimal-8.0 doesn't provide yet on the following repository.
https://repo.mysql.com/yum/mysql-8.0-community/docker/el/8/SRPMS/
Currently, Mroonga build with MySQL 8.0.38.
So, the build of Mroonga for mysql-community-minimal-8.0 need the SRPM of mysql-community-minimal-8.0.
We disable build and test for mysql-community-minimal-8.0 temporality until the SRPM of mysql-community-minimal-8.0 provide.
=> ci: disable mysql-community-minimal-8.0 temporality

doc/locale/ja/LC_MESSAGES/contribution/documentation.po, doc/source/contribution/documentation.md
GitHub: ref GH-707
Update the commands using `CMake` instead of `GNU Autotools`.
Because we will drop using `GNU Autotools` in near future.
=> doc contribution/documentation: update initial configuration for building documentation

doc/locale/ja/LC_MESSAGES/contribution/documentation.po, doc/source/contribution/documentation.md
GitHub: fix GH-707
Update the commands using CMake instead of GNU Autotools. Because we will drop using GNU Autotools in near future.
=> doc contribution/documentation: update 'confirm generated document'

doc/locale/ja/LC_MESSAGES/install/others.po, doc/source/install/others.md
GtiHub: ref GH-710
We will drop using GNU Autotools in near future. That's why we should update documentation using CMake.
=> doc install/others: update MySQL's build step using CMake

packages/percona-server-8.0-mroonga/yum/percona-server-8.0-mroonga.spec.in
Because Percona Server for MySQL 8.0.37-29 had been released.
=> packages percona-server-8.0: bump PerconaServer version

.github/workflows/linux.yml, packages/mysql-8.0-mroonga/apt/ubuntu-focal/Dockerfile
This PR support Mroonga on Ubuntu 20.04 with mysql-8.0.
This PR doesn't support Ubuntu 20.04 with mysql-community-8.0.
I will support Ubuntu 20.04 with mysql-community-8.0 in the other PR.
=> ci ubuntu: add missing test for Ubuntu 20.04 (focal) with mysql-8.0

.github/workflows/linux.yml, packages/mysql-community-8.0-mroonga/Rakefile, packages/mysql-community-8.0-mroonga/apt/ubuntu-focal/Dockerfile
This PR build and test the package of Mroonga for Ubntu 20.04 with mysql-community-8.0 same as the following tests.
* https://github.com/mroonga/mroonga/actions/runs/10293925162/job/28491156447
* https://github.com/mroonga/mroonga/actions/runs/10293925162/job/28491156618
=> ci ubuntu: add missing test for Ubuntu 20.04 (focal) with mysql-community-8.0

ha_mroonga.cpp, mrn_mysql_compat.h, packages/mariadb-10.11-mroonga/yum/mariadb-10.11-mroonga.spec.in, packages/mariadb-10.5-mroonga/yum/mariadb-10.5-mroonga.spec.in, packages/mariadb-10.6-mroonga/yum/mariadb-10.6-mroonga.spec.in
Because MariaDB 10.11.9, 10.6.19, and 10.5.26 have been released.
However, the current version of Mroonga with the above MariaDBs fail build as below.
```
ha_mroonga.cpp: In member function ‘int ha_mroonga::create_share_for_create() const’:
ha_mroonga.cpp:3755:25: error: no match for ‘operator&&’ (operand types are ‘TABLE_LIST*’ and ‘const LEX_CSTRING’ {aka ‘const st_mysql_const_lex_string’})
3755 |   if (lex->query_tables && lex->query_tables->get_table_name()) {
|       ~~~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|            |                                                |
|            TABLE_LIST*                                      const LEX_CSTRING {aka const st_mysql_const_lex_string}
ha_mroonga.cpp:3755:25: note: candidate: ‘operator&&(bool, bool)’ (built-in)
``` …
=> mariadb: add support for MariaDB 10.11.9/10.6.19/10.6.26

ha_mroonga.cpp, ha_mroonga.hpp, mrn_mysql_compat.h
This PR is the part of support for MariaDB 11.0.4 LTS.
I fail to build of Mroonga with MariaDB 11.0.4 by the following error.
```
n file included from mroonga.dev/ha_mroonga.cpp:108:
mroonga.dev/ha_mroonga.hpp:695:10: error: conflicting return type specified for ‘virtual double ha_mroonga::scan_time()’
695 |   double scan_time() mrn_override;
|          ^~~~~~~~~
In file included from /mariadb-11.4.2/sql/log.h:20,
from /mariadb-11.4.2/sql/sql_class.h:29,
from /mroonga.dev/mrn_mysql.h:57,
from /mroonga.dev/ha_mroonga.cpp:25:
/mariadb-11.4.2/sql/handler.h:3765:27: note: overridden function is ‘virtual IO_AND_CPU_COST handler::scan_time()’
3765 |   virtual IO_AND_CPU_COST scan_time()
|                           ^~~~~~~~~
```
The cause of this error by the following MaraiDB's modification. …
=> mariadb 11.0: Use IO_AND_COST type instead of double

ha_mroonga.cpp, ha_mroonga.hpp, mrn_mysql_compat.h
This PR is the part of support for MariaDB 11.0.4 LTS.
I fail to build of Mroonga with MariaDB 11.0.4 by the following error.
```
/mroonga.dev/ha_mroonga.cpp:14187:48: error: no matching function for call to ‘ha_mroonga::multi_range_read_info_const(uint&, RANGE_SEQ_IF*&, void*&, uint&, uint*&, uint*&, Cost_estimate*&)’
14187 |     rows = handler::multi_range_read_info_const(keyno, seq, seq_init_param,
|            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
14188 |                                                 n_ranges, bufsz, flags, cost);
|                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /mariadb-11.4.2/sql/log.h:20,
from /mariadb-11.4.2/sql/sql_class.h:29,
from /mroonga.dev/mrn_mysql.h:57,
from …
```
=> mariaddb 11.0: add a new argument into handler::multi_range_read_info_const()

ha_mroonga.hpp
This PR is the part of support for MariaDB 11.4 LTS.
I fail to build of Mroonga with MariaDB 11.4.2 by the following error.
```
/mroonga.dev/ha_mroonga.cpp: In member function ‘int ha_mroonga::wrapper_open(const char*, int, uint)’:
/mroonga.dev/ha_mroonga.hpp:418:48: error: ‘HA_KEY_SWITCH_ALL’ was not declared in this scope
418 | #  define MRN_HANDLER_DISABLE_INDEXES_ALL_ARGS HA_KEY_SWITCH_ALL
|                                                ^~~~~~~~~~~~~~~~~
/mroonga.dev/ha_mroonga.hpp:418:48: note: in definition of macro ‘MRN_HANDLER_DISABLE_INDEXES_ALL_ARGS’
418 | #  define MRN_HANDLER_DISABLE_INDEXES_ALL_ARGS HA_KEY_SWITCH_ALL
|                                                ^~~~~~~~~~~~~~~~~
/mroonga.dev/ha_mroonga.cpp: In member function ‘int …
```
=> mariadb 11.4: follow enable_indexes() and disable_indexes() API change

ha_mroonga.cpp, ha_mroonga.hpp, mrn_mysql_compat.h
This PR is the part of support for MariaDB 11.4 LTS.
I fail to build of Mroonga with MariaDB 11.4.2 by the following error.
```
/mroonga.dev/ha_mroonga.cpp: In member function ‘double ha_mroonga::wrapper_read_time(uint, uint, ha_rows)’:
/mroonga.dev/ha_mroonga.cpp:14964:22: error: ‘read_time’ is not a member of ‘handler’
14964 |       res = handler::read_time(index, ranges, rows);
|                      ^~~~~~~~~
/mroonga.dev/ha_mroonga.cpp:14969:25: error: ‘class handler’ has no member named ‘read_time’; did you mean ‘scan_time’?
14969 |     res = wrap_handler->read_time(share->wrap_key_nr[index], ranges, rows);
|                         ^~~~~~~~~
|                         scan_time
/mroonga.dev/ha_mroonga.cpp:14975:25: error: ‘class handler’ has no member named ‘read_time’; did you mean …
```
=> mariadb 11.4: use keyread_time() and rnd_pos_time() instead of read_time()

lib/mrn_parameters_parser.cpp, mrn_mysql_compat.h
This PR is the part of support for MariaDB 11.4 LTS.
I fail to build of Mroonga with MariaDB 11.4.2 by the following error.
```
/mroonga.dev/lib/mrn_parameters_parser.cpp: In member function ‘const char* mrn::ParametersParser::tokenizer()’:
/mroonga.dev/lib/mrn_parameters_parser.cpp:194:27: error: ‘ER_WARN_DEPRECATED_SYNTAX’ was not declared in this scope
194 |                           ER_WARN_DEPRECATED_SYNTAX,
|                           ^~~~~~~~~~~~~~~~~~~~~~~~~
```
The cause of this error by the following MaraiDB's modification.
https://github.com/MariaDB/server/commit/df4bfefbb8f670a986cd9ebe376fe09248dba4a2
`warn_deprecated()` require deprecated version.
However, backward compatibility is important for Mroonga. Therefore we rarely remove deprecated features.
So, Mroonga output only …
=> mariadb 11.4: follow push_warning_printf() API change

mrn_mysql_compat.h
This problem is same as #752.
---
The current version of Mroonga with the MariaDB 11.4.3 fail build as below.
```
ha_mroonga.cpp: In member function ‘int ha_mroonga::create_share_for_create() const’:
ha_mroonga.cpp:3755:25: error: no match for ‘operator&&’ (operand types are ‘TABLE_LIST*’ and ‘const LEX_CSTRING’ {aka ‘const st_mysql_const_lex_string’})
3755 |   if (lex->query_tables && lex->query_tables->get_table_name()) {
|       ~~~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|            |                                                |
|            TABLE_LIST*                                      const LEX_CSTRING {aka const st_mysql_const_lex_string}
ha_mroonga.cpp:3755:25: note: candidate: ‘operator&&(bool, bool)’ (built-in)
```
Because theses versions modify return value …
=> mariadb 11.4: follow get_table_name() and get_db_name() API change

ha_mroonga.cpp, ha_mroonga.hpp, mrn_mysql_compat.h
This PR is the part of support for MariaDB 11.4 LTS.
I fail to build of Mroonga with MariaDB 11.4.3 by the following error.
```
2024-08-27T05:11:48.3976514Z ha_mroonga.hpp:841:7: error: 'int ha_mroonga::get_foreign_key_list(THD*, List<st_foreign_key_info>*)' marked 'override', but does not override
2024-08-27T05:11:48.3977826Z    int get_foreign_key_list(THD *thd,
2024-08-27T05:11:48.3979650Z        ^~~~~~~~~~~~~~~~~~~~
2024-08-27T05:11:48.3981492Z ha_mroonga.hpp:843:7: error: 'int ha_mroonga::get_parent_foreign_key_list(THD*, List<st_foreign_key_info>*)' marked 'override', but does not override
2024-08-27T05:11:48.3982876Z    int get_parent_foreign_key_list(THD *thd,
2024-08-27T05:11:48.3983903Z        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-08-27T05:11:48.3988143Z In file included from …
```
=> mariadb 11.4: follow get_foreign_key_list() and get_parent_foreign_key_list() API change

ha_mroonga.cpp, ha_mroonga.hpp
`ranges` is `ulong` is correct.
https://github.com/MariaDB/server/blob/b66cdbd1eaeed7e96317a03a190c496fd062ec71/storage/mroonga/ha_mroonga.cpp#L13077-L13121
=> Fix keyread_time() argument type

Rakefile
We will drop support for GNU Autotools. This is a part of the work. We can use `rake release:document:update` instead of `make update-document`.
Usage:
```
$ rake release:document:update BUILD_DIR=../build-dir/mroonga MROONGA_ORG_DIR=../mroonga.org
```
=> Implement "make update-document" by Ruby

.github/workflows/linux.yml, packages/mysql-community-minimal-8.0-mroonga/Rakefile, packages/mysql-community-minimal-8.0-mroonga/yum/almalinux-9/Dockerfile, packages/mysql-community-minimal-8.0-mroonga/yum/mysql-community-minimal-8.0-mroonga.spec.in
This package need to create Mroonga's Docker image.
Mroonga's Docker image base on MySQL official docker image( https://hub.docker.com/_/mysql ).
Currently, MySQL official docker image base on Oracle Linux 9.
Ref: https://github.com/docker-library/mysql/blob/3e6dfd03b956727c7fb5b30360512a11751a3e9d/8.0/Dockerfile.oracle
However, we are only providing mysql-community-minimal-8.0 for AlmaLinux 8 currently.
So, we need to provide mysql-community-minimal-8.0 for AlmaLinux 9 to update Mroonga's Docker image.
=> packages mysql-community-server-minimal-8.0: add support for almalinux 9

ha_mroonga.cpp, mysql-test/mroonga/storage/column/datetime/fractional_seconds/r/null.result, mysql-test/mroonga/storage/column/datetime/fractional_seconds/t/null.test
GitHub: GH-789
The current implementation ignores NULL. It means that we don't update index for NULL.
But it causes `index_column_diff` false positive.
`DATETIME` with fraction seconds' NULL is processed as `1970-01-01 00:00:00.0` in Groonga. Because Groonga uses the default value for NULL. `index_column_diff` uses `1970-01-01 00:00:00.0` for NULL in the expected posting lists. It causes false positive.
If we use `1970-01-01 00:00:00.0` instead of ignoring for NULL, we can avoid the false positive. It also enables that we can search NULL column value record by `1970-01-01 00:00:00.0`. In general, it'll be useful but this is an incompatible change. But it'll be acceptable because NULL behavior is undefined by definition.
=> datetime fraction seconds: update index for NULL with `1970-01-01 00:00:00.0` to support index_column_diff

mysql-test/mroonga/include/mroonga/skip_windows.inc, mysql-test/mroonga/storage/column/datetime/fractional_seconds/r/null.result, mysql-test/mroonga/storage/column/datetime/fractional_seconds/t/null.test
The following "out of range" error occurred only on Windows' MariaDB when the datetime
value "1970-01-01 00:00:00.0" was set. So we decided to skip this test on only Windows.
```
mysqltest: At line 34: query 'INSERT INTO diaries VALUES ("zero day", "1970-01-01 00:00:00.0")' failed: 1264: Out of range value for column 'created_at' at row 1
```
Note that it might be a valid value because it's between `1000-01-01 00:00:00.000000` - `9999-12-31 23:59:59.999999`: https://mariadb.com/kb/en/datetime/#supported-values
But the error occurred.
=> test datetime fraction seconds: skip `1970-01-01 00:00:00.0` insert test on Windows

ha_mroonga.cpp, mysql-test/mroonga/storage/column/double/r/null.result, mysql-test/mroonga/storage/column/double/t/null.test, mysql-test/mroonga/storage/column/float/r/null.result, mysql-test/mroonga/storage/column/float/t/null.test
GitHub: GH-789
The current implementation ignores `NULL`. It means that we don't update index for `NULL`.
But it causes `index_column_diff` false positive.
The `float` and `double` with `NULL` is processed as `0.0` in Groonga. Because Groonga uses the default value for `NULL`.
`index_column_diff` uses `0.0` for `NULL` in the expected posting lists. It causes false positive.
If we use `0.0` instead of ignoring for `NULL`, we can avoid the false positive.
It also enables that we can search `NULL` column value record by `0.0`.
In general, it'll be useful but this is an incompatible change.
But it'll be acceptable because `NULL` behavior is undefined by definition.
=> {float,double}: update index for `NULL` with `0.0` to support `index_column_diff`

ha_mroonga.cpp, mysql-test/mroonga/storage/column/timestamp/fractional_seconds/r/null.result, mysql-test/mroonga/storage/column/timestamp/fractional_seconds/t/null.test
GitHub: GH-789
The current implementation ignores `NULL`. It means that we don't update index for `NULL`. But it causes `index_column_diff` false positive.
`TIMESTAMP` with fraction seconds' `NULL` is processed as `0000-00-00 00:00:00.0` in Groonga. Because Groonga uses the default value for `NULL`. `index_column_diff` uses `0000-00-00 00:00:00.0` for `NULL` in the expected posting lists. It causes false positive.
If we use `0000-00-00 00:00:00.0` instead of ignoring for `NULL`, we can avoid the false positive. It also enables that we can search `NULL` column value record by `0000-00-00 00:00:00.0`. In general, it'll be useful but this is an incompatible change. But it'll be acceptable because `NULL` behavior is undefined by definition.
=> timestamp fraction seconds: update index for `NULL` with `0000-00-00 00:00:00.0` to support `index_column_diff`

ha_mroonga.cpp, mysql-test/mroonga/storage/column/enum/r/null.result, mysql-test/mroonga/storage/column/enum/t/null.test
GitHub: GH-789
The current implementation ignores `NULL`. It means that we don't update index for `NULL`. But it causes `index_column_diff` false positive. `ENUM` with `NULL` is processed as `0` in Groonga. Because Groonga uses the default value for `NULL`. `ENUM` value is a string in user level but it's integer in MySQL/MariaDB internal. `NULL` `ENUM` value is `NULL` in MySQL/MariaDB internal and invalid `ENUM` value (`''`) is `0` in MySQL/MariaDB internal. We use `0` not `NULL` for Groonga because Groonga doesn't support `NULL`. The `index_column_diff` uses `0` for `NULL` in the expected posting lists. It causes false positive.
If we use `0` instead of ignoring for `NULL`, we can avoid the false positive. It also enables that we can search `NULL` column value record by `''` (or `0`).
In …
=> enum: update index for `NULL` with `0` to support `index_column_diff`

ha_mroonga.cpp, mysql-test/mroonga/storage/column/set/r/null.test, mysql-test/mroonga/storage/column/set/t/null.test
GitHub: GH-789
The current implementation ignores `NULL`. It means that we don't update index for `NULL`. But it causes `index_column_diff` false positive. `SET` with `NULL` is processed as `0` in Groonga.
Because Groonga uses the default value for `NULL`. `SET` value is a string in user level, but it's integer in MySQL/MariaDB internal. `NULL` `SET` value is `NULL` in MySQL/MariaDB internal and  an empty `SET` value (`''`) is `0` in MySQL/MariaDB internal. We use `0` not `NULL` for Groonga because Groonga doesn't support `NULL`. The `index_column_diff` uses `0` for `NULL` in the expected posting lists. It causes false positive.
If we use `0` instead of ignoring for `NULL`, we can avoid the false positive. It also enables that we can search `NULL` column value record by `''` (or `0`).
In …
=> set: update index for `NULL` with `0` to support `index_column_diff`

ha_mroonga.cpp, mysql-test/mroonga/storage/column/year/r/null.result, mysql-test/mroonga/storage/column/year/t/null.test
GitHub: GH-789
The current implementation ignores `NULL`. It means that we don't update index for `NULL`. But it causes `index_column_diff` false positive. `YEAR` with `NULL` is processed as `1970` in Groonga. Because Groonga uses the default value for `NULL`. `index_column_diff` uses `1970` for `NULL` in the expected posting lists. It causes false positive.
If we use `1970` instead of ignoring for `NULL`, we can avoid the false positive. It also enables that we can search `NULL` column value record by `1970`.
In general, it'll be useful but this is an incompatible change. But it'll be acceptable because `NULL` behavior is undefined by definition.
=> year: update index for `NULL` with `1970` to support `index_column_diff`

ha_mroonga.cpp, mysql-test/mroonga/storage/column/time/r/null.result, mysql-test/mroonga/storage/column/time/t/null.test
GitHub: GH-789
The current implementation ignores `NULL`. It means that we don't update index for `NULL`. But it causes `index_column_diff` false positive.
`time` with `NULL` is processed as  `0` (`00:00:00`  in MySQL/MariaDB) in Groonga. Because Groonga uses the default value for `NULL`. `index_column_diff` uses `0` for `NULL` in the expected posting lists. It causes false positive.
If we use `0`( `00:00:00`  in MySQL/MariaDB) instead of ignoring for `NULL`, we can avoid the false positive. It also enables that we can search `NULL` column value record by `00:00:00`. In general, it'll be useful but this is an incompatible change. But it'll be acceptable because NULL behavior is undefined by definition.
=> time: update index for `NULL` with `00:00:00` to support `index_column_diff`

ha_mroonga.cpp, mysql-test/mroonga/storage/column/datetime/r/null.result, mysql-test/mroonga/storage/column/datetime/t/null.test
GitHub: GH-789
The current implementation ignores `NULL`. It means that we don't update index for `NULL`. But it causes `index_column_diff` false positive.
`DATETIME` with `NULL` is processed as `0` in Unix time (`1970-01-01 00:00:00` in MySQL/MariaDB) in Groonga. Because Groonga uses the default value for `NULL`. `index_column_diff` uses `0` for `NULL` in the expected posting lists. It causes false positive.
If we use `0` in Unix time (`1970-01-01 00:00:00` in MySQL/MariaDB) instead of ignoring for `NULL`, we can avoid the false positive. It also enables that we can search `NULL` column value record by `1970-01-01 00:00:00`. In general, it'll be useful but this is an incompatible change. But it'll be acceptable because NULL behavior is undefined by definition.
=> datetime: update index for `NULL` with `1970-01-01 00:00:00` to support `index_column_diff`

ha_mroonga.cpp, mysql-test/mroonga/storage/column/timestamp/r/null.result, mysql-test/mroonga/storage/column/timestamp/t/null.test
GitHub: GH-789
The current implementation ignores `NULL`. It means that we don't update index for `NULL`. But it causes `index_column_diff` false positive.
`timestamp` with `NULL` is processed as  `0` (`0000-00-00 00:00:00`  in MySQL/MariaDB) in Groonga. Because Groonga uses the default value for `NULL`. `index_column_diff` uses `0` for `NULL` in the expected posting lists. It causes false positive.
If we use `0`( `0000-00-00 00:00:00`  in MySQL/MariaDB) instead of ignoring for `NULL`, we can avoid the false positive. It also enables that we can search `NULL` column value record by `0000-00-00 00:00:00`. In general, it'll be useful but this is an incompatible change. But it'll be acceptable because NULL behavior is undefined by definition.
Note: MySQL enables STRICT_ALL_TABLES by default …
=> timestamp: update index for `NULL` with `0000-00-00 00:00:00` to support `index_column_diff`

ha_mroonga.cpp, mysql-test/mroonga/storage/column/date/r/null.result, mysql-test/mroonga/storage/column/date/t/null.test
GitHub: GH-789
The current implementation ignores `1970-01-01`. It means that we don't update index for `NULL`. But it causes `index_column_diff` false positive.
`DATE` with `NULL` is processed as `0` (`1970-01-01` in MySQL/MariaDB) in Groonga. Because Groonga uses the default value for `NULL`. `index_column_diff` uses `0` for `NULL` in the expected posting lists. It causes false positive.
If we use `0`( `1970-01-01` in MySQL/MariaDB) instead of ignoring for `NULL`, we can avoid the false positive. It also enables that we can search `NULL` column value record by `1970-01-01`. In general, it'll be useful but this is an incompatible change. But it'll be acceptable because NULL behavior is undefined by definition.
=> date: update index for `NULL` with `1970-01-01` to support `index_column_diff`

mysql-test/mroonga/storage/column/date/t/null.test
This is a workaround for Windows.
MySQL/MariaDB accepts `'1000-01-01'` to `'9999-12-31'` as valid range for the `DATE` type. But Mroonga processes it as Unix time. Mroonga uses `struct tm` to convert `YYYY-MM-DD` value in MySQL/MariaDB to Unix time. It causes an "out of range" error for `1970-01-01` or older. We should fix it but we skip the case for now.
Here is the error message:
```
mroonga/storage/column/date.null         w3 [ fail ]
Test ended at 2024-10-11 17:32:11
CURRENT_TEST: mroonga/storage/column/date.null
mysqltest: At line 32: query 'INSERT INTO diaries VALUES ('epoch date', '1970-01-01')' failed: 1264: Out of range value for column 'created_on' at row 1
The result from queries just before the failure was:
DROP TABLE IF EXISTS diaries;
CREATE TABLE diaries (
name …
```
=> date: skip the test about epoch date on Windows

ha_mroonga.cpp, mysql-test/mroonga/storage/column/bit/r/null.result, mysql-test/mroonga/storage/column/bit/t/null.test
GitHub: GH-789
The current implementation ignores `NULL`. It means that we don't update index for `NULL`. But it causes `index_column_diff` false positive. `BIT` with `NULL` is processed as `0` in Groonga. Because Groonga uses the default value for `NULL`. `NULL` `BIT` value is `NULL` in MySQL/MariaDB internal. We use `0` not `NULL` for Groonga because Groonga doesn't support `NULL`. The `index_column_diff` uses `0` for `NULL` in the expected posting lists. It causes false positive.
If we use `0` instead of ignoring for `NULL`, we can avoid the false positive. It also enables that we can search `NULL` column value record by `b'0'`.
In general, it'll be useful but this is an incompatible change. But it'll be acceptable because `NULL` behavior is undefined by definition.
=> bit: update index for `NULL` with `0` (`b'0'`) to support `index_column_diff`

ha_mroonga.cpp, mysql-test/mroonga/storage/column/char/r/null.result, mysql-test/mroonga/storage/column/char/t/null.test
GitHub: GH-789
Mroonga doesn't support `NULL`. So inserting `NULL` to Mroonga table is undefined by definition.
This change uses padded empty string for `NULL` for convenience. The current behavior just uses the default value, an empty (not padded) string. This is an incompatible change. But we can do it because this behavior was undefined. Users who depend on this behavior must not exist.
=> char: use padded empty string for `NULL`

ha_mroonga.cpp, mysql-test/mroonga/storage/column/blob/r/null.result, mysql-test/mroonga/storage/column/blob/t/null.test, mysql-test/mroonga/storage/column/long_blob/r/null.result, mysql-test/mroonga/storage/column/long_blob/t/null.test, mysql-test/mroonga/storage/column/medium_blob/r/null.result, mysql-test/mroonga/storage/column/medium_blob/t/null.test
GitHub: GH-789
The current Mroonga ignores `NULL` values for `{,MEDIUM,LARGE}BLOB`. This doesn't change the current behavior. This still ignores `NULL` values but `NULL` check code is moved to `generic_store_bulk_blob()` from `storage_write_row()` like other types. `storage_write_row()` ignores empty bulk after `generic_store_bulk_blob()` call. So this doesn't change the current behavior.
We want to remove `if (field->is_null() && ...) continue` for `grn_obj_set_value()` entirely in `storage_write_row()` eventually. This is a step for it.
=> blob: use empty string for `NULL` explicitly

ha_mroonga.cpp, mysql-test/mroonga/storage/column/varchar/r/null.result, mysql-test/mroonga/storage/column/varchar/t/null.test
GitHub: GH-789
The current Mroonga ignores `NULL` values for `VARCHAR`. This doesn't change the current behavior.
This still ignores `NULL` values but `NULL` check code is moved to `generic_store_bulk_variable_size_string()` from `storage_write_row()` like other types. `storage_write_row()` ignores empty bulk after `generic_store_bulk_variable_size_string()` call. So this doesn't change the current behavior.
We want to remove `if (field->is_null() && ...) continue` for `grn_obj_set_value()` entirely in `storage_write_row()` eventually. This is a step for it.
=> varchar: use empty string for NULL explicitly

doc/files.am, doc/files.cmake
This change fixed the following CI error because the generated file list has been changed from Sphinx 8.1.3.
```
cp: cannot stat './html/_static/styles/bootstrap.css': No such file or directory
```
ref: https://github.com/mroonga/mroonga/actions/runs/11470945099/job/31921042894#step:11:3614
We have updated the following commands.
```console
$ cmake \
-Smroonga\
-Bmroonga.doc \
--preset=doc \
-DMYSQL_BUILD_DIR=$HOME/work/cpp/mariadb-11.4.3.build \
-DMYSQL_CONFIG=$HOME/work/cpp/mariadb-11.4.3.build/scripts/mysql_config \
-DMYSQL_SOURCE_DIR=$HOME/work/cpp/mariadb-11.4.3
$ ninja doc_update_files -C ./mroonga.doc
```
=> doc: update the generated file list by Shpinx v8.1.3

ha_mroonga.cpp, ha_mroonga.hpp, mrn_mysql_compat.h
This PR is the part of support for MariaDB 11.4.4 LTS.
See:
https://github.com/MariaDB/server/commit/12a91b57e27b979819924cf89614e6e51f24b37b
https://jira.mariadb.org/browse/MDEV-35351
=> mariadb 11.4: follow get_foreign_key_list()/get_parent_foreign_key_list() API change

ha_mroonga.cpp, ha_mroonga.hpp, mrn_mysql_compat.h
This PR is the part of support for MariaDB 11.4.4 LTS.
Fix: GH-822
See: MariaDB/server@45298b730b
=> mariadb 11.4: follow referenced_by_foreign_key() API change

doc/source/install/centos.md
The following warning:
```
checking consistency... doc/source/install/centos.md: WARNING: document isn't included in any toctre
```
=> docs: Add `:orphan:` to `install/centos.md`

.github/workflows/install.yml, packages/yum/install_test.sh
Related: GitHub GH-837.
This adds support for only AlmaLinux 8 and Mariadb 10.5.
=> ci: Add install test for AlmaLinux 8 with Mariadb 10.5

.github/workflows/install.yml, packages/yum/install_test.sh
Related: GitHub GH-837.
This adds support for only AlmaLinux 9 and Mariadb 10.5.
This modification passed CI in the following URL.
https://github.com/komainu8/mroonga/actions/runs/12706476645
=> ci: add install test for AlmaLinux 9 with MariaDB 10.5

.github/workflows/install.yml
Related: GitHub GH-837.
This adds support for only AlmaLinux 8 and Mariadb 10.6.
=> ci: add install test for AlmaLinux 8 with MariaDB 10.6

.github/workflows/install.yml
This adds support for only AlmaLinux 9 and Mariadb 10.6.
=> ci: add install test for AlmaLinux 9 with MariaDB 10.6

.github/workflows/install.yml
This adds support for only AlmaLinux 8 and Mariadb 10.11.
=> ci: add install test for AlmaLinux 8 with MariaDB 10.11

.github/workflows/install.yml
This adds support for only AlmaLinux 9 and Mariadb 10.11.
=> ci: add install test for AlmaLinux 9 with MariaDB 10.11

.github/workflows/install.yml
This adds support for only AlmaLinux 8 and Mariadb 11.4.
=> ci: add install test for AlmaLinux 8 with MariaDB 11.4

.github/workflows/install.yml
This adds support for only AlmaLinux 9 and Mariadb 11.4.
=> ci: add install test for AlmaLinux 9 with MariaDB 11.4

doc/source/install/almalinux.rst
These URLs are suggested by MariaDB official download page as below.
https://mariadb.org/download/?t=repo-config&d=Red+Hat+Enterprise+Linux+8&v=10.5&r_m=yamagata-university
=> doc install: use more suitable URLs for MariaDB official repository

.github/workflows/install.yml, packages/yum/install_test.sh
This adds support for only AlmaLinux 8 and MySQL Community Server 8.0.
=> ci: add install test for AlmaLinux 8 with MySQL Community Server 8.0

.github/workflows/install.yml
This adds support for only AlmaLinux 9 and MySQL Community Server 8.0.
=> ci: add install test for AlmaLinux 9 with MySQL Community Server 8.0

.github/workflows/install.yml
This adds support for only AlmaLinux 8 and MySQL Community Server 8.4.
=> ci: add install test for AlmaLinux 8 with MySQL Community Server 8.4

.github/workflows/install.yml, packages/yum/install_test.sh
This adds support for only AlmaLinux 9 and MySQL Community Server minimal 8.0.
=> ci: add install test for AlmaLinux 9 with MySQL Community Server minimal 8.0

.github/workflows/install.yml, packages/yum/install_test.sh
This adds support for only AlmaLinux 8 and Percona Server 8.0.
=> ci: add install test for AlmaLinux 8 with Percona Server 8.0

.github/workflows/install.yml
This adds support for only AlmaLinux 9 and Percona Server 8.0.
=> ci: add install test for AlmaLinux 9 with Percona Server 8.0

packages/yum/test.sh
Because we have already released Mroonga for MySQL Community Server 8.4 since 14.04.
=> ci: enable upgrade test for mysql-community-server-8.4-mroonga

packages/yum/test.sh
Because we have arleady released Mroonga 14.04.
=> ci: enable upgrade test for mariadb-*-mroonga

doc/CMakeLists.txt, doc/Gemfile
* `--quiet`
* It is easier to see output related to errors
* `--fail-on-warning`
* This option causes the build to fail on warnings
* It makes it easier to notice mistakes
* Added `red-datasets` to Gemfile because of warning output at build
These are the same as the settings for building documents in groonga/groonga.
=> doc: Add the `--quiet` and `--fail-on-warning` options to `sphinx-build`

doc/locale/ja/LC_MESSAGES/install/others.po, doc/source/install/others.md
=> docs: Remove unnecessary character from the URL of the link

packages/mroonga-package-task.rb
During the Mroonga release, an following error occurred because the rake task for downloading source archives was not defined.
This PR introduces the necessary rake task to handle the downloading of source archives.
```
$ rake ubuntu DPUT_CONFIGURATION_NAME=groonga-ppa-nightly DPUT_INCOMING="~groonga/ubuntu/nightly"
cd mariadb-10.5-mroonga
/home/otegami/.rbenv/versions/3.3.7/bin/ruby -S rake ubuntu
cd -
cd mariadb-10.6-mroonga
/home/otegami/.rbenv/versions/3.3.7/bin/ruby -S rake ubuntu
rake aborted!
Don't know how to build task '/home/otegami/work/cpp/mroonga.clean/mroonga-14.13.tar.gz' (See the list of available tasks with `rake --tasks`)
Tasks: TOP => ubuntu => ubuntu:upload => ubuntu:upload:jammy => mariadb-10.6-mroonga-14.13.tar.gz
(See full trace by running task with --trace)
rake …
```
=> packages: donwload soruce archive automatically

doc/source/install/debian.rst
Fix: GH-867
apt-transport-https is a transitional package.
=> docs install: remove a needless dependency package

doc/source/install/debian.rst
Fix: GH-868
We can use codename directly like we did for groonga-apt-source.
So, we don't need to use lsb_release for apache-arrow-apt-source.
=> docs install/debian: don't use lsb_release

packages/apt/test.sh
This reverts commit a3169a8f197cd731c5a55c42193f37e73b054553.
Because we have already released Mroonga 14.10.
=> Revert "packages apt test: disable upgrade test temporally until next release (#818)"

.github/workflows/linux.yml, packages/apt/test.sh, packages/yum/test.sh
Upgrade tests could fail in due to the existed package's external dependency updates (e.g. new versions of MariaDB/MySQL) that do not affect the functionality of the release package. And also, we have confirmed that package upgrades work correctly in non-release testing environments.
To avoid blocking new package releases due to irrelevant upgrade test failures, we skip upgrade test on only release.
=> ci test: skip upgrade tests on release

ha_mroonga.cpp, lib/mrn_context_pool.cpp, lib/mrn_context_pool.hpp, mysql-test/mroonga/storage/variable/n_workers/r/2_cpu.result, mysql-test/mroonga/storage/variable/n_workers/r/all_cpu.result, mysql-test/mroonga/storage/variable/n_workers/r/global.result, mysql-test/mroonga/storage/variable/n_workers/r/no_parallel.result, mysql-test/mroonga/storage/variable/n_workers/r/startup.result, mysql-test/mroonga/storage/variable/n_workers/t/2_cpu.test, mysql-test/mroonga/storage/variable/n_workers/t/all_cpu.test, mysql-test/mroonga/storage/variable/n_workers/t/global.test, mysql-test/mroonga/storage/variable/n_workers/t/no_parallel.test, mysql-test/mroonga/storage/variable/n_workers/t/startup-master.opt, mysql-test/mroonga/storage/variable/n_workers/t/startup.test
By setting the value of `mroonga_n_workers` to Groonga, we can use Groonga's parallel processing.
=> Add `mroonga_n_workers` to the system variables

packages/mariadb-10.5-mroonga/yum/mariadb-10.5-mroonga.spec.in
If we specify only MariaDB-client and MariaDB-server, different versions of depended MariaDB-common and MariaDB-shared packages may be installed:
```
Installing:
mariadb-10.5-mroonga       x86_64  14.14-1.el8                             groonga-almalinux  191 k
Installing dependencies:
MariaDB-client             x86_64  10.5.27-1.el8                           mariadb             14 M
MariaDB-common             x86_64  10.5.28-1.el8                           mariadb             88 k
MariaDB-server             x86_64  10.5.27-1.el8                           mariadb             27 M
MariaDB-shared             x86_64  10.5.28-1.el8                           mariadb            115 k
```
=> packages mariadb-10.5: specify all related MariaDB packges with version explicitly

packages/mariadb-10.6-mroonga/yum/mariadb-10.6-mroonga.spec.in
If we specify only MariaDB-client and MariaDB-server, different versions of depended MariaDB-common and MariaDB-shared packages may be installed:
```
Installing:
mariadb-10.6-mroonga       x86_64  14.14-1.el8                             groonga-almalinux  187 k
Installing dependencies:
MariaDB-client             x86_64  10.6.20-1.el8                           mariadb             15 M
MariaDB-common             x86_64  10.6.21-1.el8                           mariadb             88 k
MariaDB-server             x86_64  10.6.20-1.el8                           mariadb             26 M
MariaDB-shared             x86_64  10.6.21-1.el8                           mariadb            128 k
```
=> packages mariadb-10.6: specify all related MariaDB packges with version explicitly

packages/yum/test.sh
Because we have already released Mroonga 15.00.
=> packages mariadb 11.4: enable upgrade test

Rakefile
We can get the next version with `String#succ`.
```
irb(main):001:0> "15.01".succ
=> "15.02"
irb(main):002:0> "15.09".succ
=> "15.10"
```
It is no longer necessary to specify in `NEW_VERSION`.
=> rake: Automatically set version

ha_mroonga.cpp
We use std::string in ha_mroonga.cpp.
However, we don't include <string>. So, Mroonga occurs error as below.
```
2025-03-25T01:19:11.1307332Z D:\a\mroonga\mroonga\mariadb\storage\mroonga\ha_mroonga.cpp(4452,8): error C2039: 'string': is not a member of 'std'
2025-03-25T01:19:11.1308280Z   std::string mrn_name_normalize(const mrn_foreign_key_name& name)
```
This PR resolve the above error.
=> Add a missing include

doc/source/developer/release.rst
Can be released by `rake release` as well as mroonga/mroonga.
https://github.com/groonga/groonga.org/pull/97
=> docs: release: Update command to run in mroonga/mroonga.org

.github/workflows/mariadb.yml
GitHub: GH-900
This change enables ccache to speed up repeated builds.
=> ci mariadb: enable ccache

udf/mrn_udf_command.cpp, udf/mrn_udf_escape.cpp, udf/mrn_udf_highlight_html.cpp, udf/mrn_udf_last_insert_grn_id.cpp, udf/mrn_udf_normalize.cpp, udf/mrn_udf_query_expand.cpp, udf/mrn_udf_snippet.cpp, udf/mrn_udf_snippet_html.cpp
Shows up in mroonga UDF tests under clang with UBSAN:
UndefinedBehaviorSanitizer: function-type-mismatch
=> mroonga_* udf correct ptr types for is_null/error

.github/workflows/windows.yml
CMake in CI environment fails with 4.0.0.
```
CMake Error at CMakeLists.txt:17 (CMAKE_MINIMUM_REQUIRED):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
-- Configuring incomplete, errors occurred!
```
We get this error with MariaDB 10.x.
MariaDB 11.x does not have this error, but fails with the same error when building Groonga.
Groonga error fixed by https://github.com/groonga/groonga/pull/2266.
=> ci: windows: Add `-DCMAKE_POLICY_VERSION_MINIMUM=3.5` option to CMake

.github/workflows/mariadb.yml
GitHub: GH-900
This changes update the CI workflow for MariaDB to enable testing of Mroonga with the main branch.
Although some tests are still failed, we will fix them in the following PRs.
=> ci mariadb: enable Mroonga test with MariaDB main

lib/mrn_field_normalizer.cpp, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_as_ci/r/french.result, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_as_ci/r/japanese_accent.result, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_as_ci/r/japanese_case.result, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_as_ci/t/french.test, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_as_ci/t/japanese_accent.test, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_as_ci/t/japanese_case.test
GitHub: GH-900
This changes also add support for the `utf8mb4_uca1400_as_ci` collation in Mroonga because MariaDB supports it from 11.5.
ref: https://github.com/groonga/groonga-normalizer-mysql
ref: https://mariadb.com/kb/en/supported-character-sets-and-collations/
We will support the other families about `utf8mb4_uca1400_*` in the following PRs.
=> mrn_field_normalizer: support `utf8mb4_uca1400_as_ci` collation

lib/mrn_field_normalizer.cpp, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_ai_cs/r/french.result, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_ai_cs/r/japanese_accent.result, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_ai_cs/r/japanese_case.result, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_ai_cs/t/french.test, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_ai_cs/t/japanese_accent.test, mysql-test/mroonga/storage/collation/utf8mb4_uca1400_ai_cs/t/japanese_case.test
GitHub: GH-900
This changes also add support for the `utf8mb4_uca1400_ai_cs` collation in Mroonga because MariaDB supports it from 11.5.
ref: https://github.com/groonga/groonga-normalizer-mysql
ref: https://mariadb.com/kb/en/supported-character-sets-and-collations/
=> mrn_field_normalizer: support `utf8mb4_uca1400_ai_cs` collation

.github/workflows/mariadb.yml
Tests against MariaDB main are currently failed until we finish tracking upstream changes. Which causes the CI to appear failed and could mask other real failures.
This adds `continue-on-error` option to the MariaDB CI as a temporary measure. Once all tests pass cleanly on MariaDB main, remove this.
=> ci mariadb: temporarily ignore test failures

packages/mroonga-package-task.rb
CDN edge nodes can serve old cached listings and prevent detecting the latest package versions. During our last release, the
package‐detection step failed because it only saw up through 8.0.41 and could not find 8.0.42, causing a build‐dependency error:
```
mysql-community-devel = 8.0.41-1.el8 is needed by mysql-community-8.0-mroonga-15.06-1.el8.x86_64
```
Using URI without a trailing slash ensures we always retrieve the newest RPM list.
URI with a trailing slash.
```console
$ curl https://repo.mysql.com/yum/mysql-8.0-community/el/9/SRPMS/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
<HEAD>
<TITLE>Index of /232905/yum/mysql-8.0-community/el/9/SRPMS</TITLE>
</HEAD>
<BODY>
<H1>Index of /232905/yum/mysql-8.0-community/el/9/SRPMS</H1>
<PRE>   Name …
```
=> release yum: use URI without a trailing slash to get RPM index

doc/locale/ja/LC_MESSAGES/news/15.po, doc/source/news/15.md
We skipped 15.06 because the dependent packages were updated during the release steps.
=> doc: add 15.07 entry

packages/mariadb-10.11-mroonga/yum/almalinux-8/Dockerfile, packages/mariadb-10.5-mroonga/yum/almalinux-8/Dockerfile, packages/mariadb-10.6-mroonga/yum/almalinux-8/Dockerfile, packages/mariadb-11.4-mroonga/yum/almalinux-8/Dockerfile, packages/mysql-community-8.0-mroonga/yum/almalinux-8/Dockerfile, packages/mysql-community-8.4-mroonga/yum/almalinux-8/Dockerfile, packages/percona-server-8.0-mroonga/yum/almalinux-8/Dockerfile, packages/yum/install_test.sh, packages/yum/test.sh
The following error in build step is raised because Groonga YUM repository doesn't serve arrow-devel-x.x.x package.
```
83.22 Error: 
83.22  Problem: cannot install the best candidate for the job
83.22   - nothing provides arrow-devel >= 20.0.0 needed by groonga-devel-15.0.9-1.el8.x86_64 from groonga-almalinux
83.22 (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
We added the official Apache Arrow repository.
=> packages yum: update Apache Arrow package URL

.github/workflows/release.yml
It's for avoiding to detect a problem on tag push.
=> ci: run release jobs as much as possible

.github/workflows/mariadb.yml, mysql-test/mroonga/wrapper/r/distinct.result, mysql-test/mroonga/wrapper/t/distinct.test
Related GH-900.
This PR resolve the following error.
```
CURRENT_TEST: mroonga/wrapper.distinct
--- /home/runner/work/mroonga/mroonga/mariadb/mysql-test/suite/mroonga/wrapper/r/distinct.result	2025-05-27 01:57:13.191770063 +0000
+++ /home/runner/work/mroonga/mroonga/mariadb/mysql-test/suite/mroonga/wrapper/r/distinct.reject	2025-05-27 01:59:55.334834725 +0000
@@ -9,5 +9,5 @@
INSERT INTO items VALUES (3, 'green');
EXPLAIN SELECT DISTINCT color FROM items;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
-1	SIMPLE	items	range	NULL	color	18	NULL	3	Using index for group-by
+1	SIMPLE	items	range	NULL	color	66	NULL	3	Using index for group-by
DROP TABLE items;
```
https://github.com/mroonga/mroonga/actions/runs/15264998418/job/42929027513#step:15:57
`mroonga/wrapper.distinct` …
=> test wrapper distinct: specify charset explicitly

.github/workflows/mariadb.yml
We are trying to submodule Mroonga in the MariaDB server. 
But we get an error, so we test if it builds as expected.
`Configure MariaDB` with `id: amd64-compile-only-minimal` fails because it is a commit that changes CI in preparation for the upcoming fix.
=> ci: mariadb: Run Configure MariaDB in compile-only-minimal as well

.github/workflows/mariadb.yml, CMakeLists.txt
Related commit:
GitHub https://github.com/MariaDB/server/commit/d98514690fc647682ac06e7b09502b4274fa3e20
=> cmake: return early if mroonga is disabled

ha_mroonga.cpp, ha_mroonga.hpp, mrn_mysql_compat.h
GitHub fixes GH-964
MariaDB 10.5 drops support with EOL, so clean up related codes.
=> Clean up code related to MariaDB 10.5

.github/workflows/windows.yml
GitHub: GH-967
This fixes the build error caused by MariaDB 11.4.8+ changes.
MariaDB commit: https://github.com/MariaDB/server/commit/9bf0492 removed the use of `INSTALL_RUNTIME_DEPENDENCIES_DEFAULT` variable and made `INSTALL_RUNTIME_DEPENDENCIES` always default to `ON`.
This commit updates our CI to use the correct flag name:
- Before: `-DINSTALL_RUNTIME_DEPENDENCIES_DEFAULT=OFF`
- After:  `-DINSTALL_RUNTIME_DEPENDENCIES=OFF`
This resolves the following error that started appearing with MariaDB 11.4.8+:
```
CMake Error at cmake_install.cmake:1653 (file):
file Could not resolve runtime dependencies:
groonga-llama.dll
FAILED: [code=1] CMakeFiles/install.util
C:\Windows\system32\cmd.exe /C "cd /D D:\a\mroonga\mroonga\build && "C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake" …
```
=> ci windows: use "INSTALL_RUNTIME_DEPENDENCIES" instead of deprecated flag

mysql-test/mroonga/storage/function/normalize/r/record.result, mysql-test/mroonga/storage/function/normalize/t/record.test
The default character encoding has changed in MariaDB 11.8, so we explicitly specify it.
This change fixes the test error caused by garbled text.
```
select version();
version()
11.4.8-MariaDB-debug-log
SHOW VARIABLES LIKE 'character_set_%';
Variable_name	Value
character_set_client	latin1
character_set_collations
character_set_connection	latin1
character_set_database	latin1
character_set_filesystem	binary
character_set_results	latin1
character_set_server	latin1
character_set_system	utf8mb3
character_sets_dir	/mariadb/mariadb-11.4.8/sql/share/charsets/
```
```
select version();
version()
11.8.3-MariaDB-debug-log
SHOW VARIABLES LIKE 'character_set_%';
Variable_name	Value
character_set_client	latin1
character_set_collations	utf8mb3=utf8mb3_uca1400_ai_ci,ucs2=ucs2_uca1400_ai_ci,utf8mb4=utf8mb4 …
```
=> test: Specify the character encoding because mroonga_normalize() test cause garbled text
