mroonga/mroonga

packages/rpm/centos/mysql56-community-mroonga.spec.in, packages/rpm/centos/percona-server-56-mroonga.spec.in
=> Start mysqld when mysqld is not running within rpm-installation.

packages/rpm/centos/percona-server-56-mroonga.spec.in
=> Apply a431ffb to percona-server-56-mroonga.

packages/rpm/centos/mysql57-community-mroonga.spec.in
Re-fix for #77 .
Discussions are in #78 comments.
=> Fix to Not using MYSQL_PWD

packages/rpm/centos/mysql57-community-mroonga.spec.in
This refers #79.
At last, I can divide eval and unnecessary variables.
=> Fix not using eval

data/install.sql.in
=> Add missing create function for mroonga_normalize()

doc/locale/ja/LC_MESSAGES/reference.po, doc/source/reference/server_variables.rst, ha_mroonga.cpp, mysql-test/mroonga/include/mroonga/check_libgroonga_support_zstd.inc, mysql-test/mroonga/include/mroonga/support_libgroonga_zstd.inc, mysql-test/mroonga/include/mroonga/unsupport_libgroonga_zstd.inc, mysql-test/mroonga/storage/column/groonga/scalar/r/support_zstd.result, mysql-test/mroonga/storage/column/groonga/scalar/r/unsupport_zstd.result, mysql-test/mroonga/storage/column/groonga/scalar/t/support_zstd.test, mysql-test/mroonga/storage/column/groonga/scalar/t/unsupport_zstd.test
This change just only support ``GRN_OBJ_COMPRESS_ZSTD`` flag.
=> Support zstd flag

configure.ac
Current latest sphinx version is 1.6.3.
=> Permit Sphinx 1.6.x

packages/windows/build-vc2017-msi-32.bat, packages/windows/build-vc2017-msi-64.bat, packages/windows/build-vc2017-zip-32.bat, packages/windows/build-vc2017-zip-64.bat, packages/windows/build-vc2017.bat
Tested on:
* Windows 10 Home Build 1703
* Visual Studio 2017
* cmake 3.9.0
=> package windows: Create building batch files for Visual Studio 2017

ha_mroonga.cpp, mysql-test/mroonga/storage/column/generated/stored/r/delete.result, mysql-test/mroonga/storage/column/generated/stored/r/insert.result, mysql-test/mroonga/storage/column/generated/stored/r/reindex.result, mysql-test/mroonga/storage/column/generated/stored/r/update.result, mysql-test/mroonga/storage/column/generated/stored/t/delete.test, mysql-test/mroonga/storage/column/generated/stored/t/insert.test, mysql-test/mroonga/storage/column/generated/stored/t/reindex.test, mysql-test/mroonga/storage/column/generated/stored/t/update.test, mysql-test/mroonga/wrapper/column/generated/stored/r/delete.result, mysql-test/mroonga/wrapper/column/generated/stored/r/insert.result, mysql-test/mroonga/wrapper/column/generated/stored/r/reindex.result, mysql-test/mroonga/wrapper/column/generated/stored/r/update.result, mysql-test/mroonga/wrapper/column/generated/stored/t/delete.test, mysql-test/mroonga/wrapper/column/generated/stored/t/insert.test, mysql-test/mroonga/wrapper/column/generated/stored/t/reindex.test, mysql-test/mroonga/wrapper/column/generated/stored/t/update.test
`` HA_GENERATED_COLUMNS`` seems to be available just by adding table flags for indexing non virtual(stored) generated column.
=> Support generated column

mysql-test/mroonga/storage/column/generated/stored/r/add_column.result, mysql-test/mroonga/storage/column/generated/stored/r/drop_column.result, mysql-test/mroonga/storage/column/generated/stored/t/add_column.test, mysql-test/mroonga/storage/column/generated/stored/t/drop_column.test, mysql-test/mroonga/wrapper/column/generated/stored/r/add_column.result, mysql-test/mroonga/wrapper/column/generated/stored/r/drop_column.result, mysql-test/mroonga/wrapper/column/generated/stored/t/add_column.test, mysql-test/mroonga/wrapper/column/generated/stored/t/drop_column.test
=> test: add more test cases for stored generated column

ha_mroonga.cpp, mrn_mysql_compat.h
#161 
I've implemented to support inplace alter table for stored generated column.
=> Support inplace alter table for stored generated column

packages/rpm/centos/percona-server-57-mroonga.spec.in, packages/yum/env.sh.in
We updated env.sh.in also.
Because added dependence library for percona-server-57-5.7.20-18.1
=> package rpm: update Percona Server 5.7

mysql-test/mroonga/storage/r/not_in.result, mysql-test/mroonga/storage/t/not_in.test
I added only test.
TODO: Add code with fixed a bug.
=> [WIP] Fix a bug that result is empty when "NOT IN" have multiple arguments

mysql-test/mroonga/storage/r/order_by_rand.result, mysql-test/mroonga/storage/t/order_by_rand.test
I added only test.
TODO: Add code with fixed a bug.
=> [WIP] Fix a bug that "ORDER BY RAND()"'s result is wrong when use "ORDER BY RAND()" and "LIMIT" at the same time

doc/locale/ja/LC_MESSAGES/install.po, doc/source/install/windows.rst
=> doc: fix broken link to installer for windows

mysql-test/mroonga/storage/column/datetime/64bit/strict_sql_mode/mariadb_10_2_or_later/r/out_of_range.result, mysql-test/mroonga/storage/column/datetime/64bit/strict_sql_mode/mariadb_10_2_or_later/t/out_of_range.test
Now full name of object is included.
See https://jira.mariadb.org/browse/MDEV-14576
=> test: follow changed error message for MariaDB 10.2 or later

doc/source/news.rst
@kenhys Could you confirm that there are no omissions and wrong information, please?
Because I wrote the wrong news before release.
=> doc: add 9.00 entry

mrn_mysql_compat.h
MRN_MYSQL_P is not defined yet.
=> Fix a typo

CMakeLists.txt, appveyor.yml
=> appveyor: move install instruction to CMakeLists.txt

doc/locale/ja/LC_MESSAGES/reference.po, doc/source/reference/server_variables.rst, doc/source/reference/sql_commands.rst
The following parameter name was changed since Mroonga 5.04.
COMMENT 'parser ...' ->
COMMENT 'tokenizer ...'
=> doc: follow parameter name change

doc/source/reference/udf/mroonga_snippet.rst, doc/source/tutorial/wrapper.rst
=> doc: specify MATCH ... AGAINST(... IN BOOLEAN MODE) explicitly

configure.ac, packages/rpm/centos/Makefile.am, packages/rpm/centos/mariadb-10.4-mroonga.spec.in, packages/yum/Makefile.am, packages/yum/build-in-vm.sh, packages/yum/build-rpm.sh
TODO:  need to fix some build error.
https://travis-ci.org/mroonga/mroonga/jobs/572162590
=> packages yum: add MariaDB 10.4 build task

packages/windows/install-mroonga.ps1
It avoids not to be initialized/terminated in incomplete state.
=> appveyor: wait at least 10 seconds for initializing/terminating phase

packages/percona-server-8.0-mroonga/yum/percona-server-80-mroonga.spec.in
=> packages percona-server-8.0: use the latest percona-server-8.0

packages/yum/test.sh
=> package yum: fix a name of test suite package for Percona Server 5.7

packages/percona-server-8.0-mroonga/yum/centos-7/Dockerfile, packages/percona-server-8.0-mroonga/yum/centos-8/Dockerfile, packages/percona-server-8.0-mroonga/yum/percona-server-8.0-mroonga.spec.in
This is testing now on CI.
I'll merge When this change will pass CI.
=> package percona-server-8.0: use the latest release

doc/locale/ja/LC_MESSAGES/install.po, doc/source/install.rst, doc/source/install/almalinux.rst
=> doc install: add a install procedure for AlmaLinux 8

doc/source/install/centos.rst
update percona-release-latest.noarch.rpm url.
=> doc centos: use the correct percona-release-latest URL

ha_mroonga.cpp, ha_mroonga.hpp, lib/mrn_timestamp_field_value_converter.hpp, packages/mysql-community-5.7-mroonga/yum/mysql-community-5.7-mroonga.spec.in, packages/mysql-community-8.0-mroonga/yum/mysql-community-8.0-mroonga.spec.in
=> packages mysql-community: use the latest release

packages/percona-server-8.0-mroonga/yum/percona-server-8.0-mroonga.spec.in
This is testing now.
I'll merge to master when all tests will pass.
=> packages percona-server-8.0: use the latest release

.github/workflows/linux.yml, packages/Rakefile, packages/mariadb-10.8-mroonga/Rakefile, packages/mariadb-10.8-mroonga/yum/almalinux-8/Dockerfile, packages/mariadb-10.8-mroonga/yum/centos-7/Dockerfile, packages/mariadb-10.8-mroonga/yum/mariadb-10.8-mroonga.spec.in, packages/yum/test.sh
=> packages mariadb-10.8: add

packages/mariadb-10.7-mroonga/yum/almalinux-8/Dockerfile, packages/mariadb-10.7-mroonga/yum/centos-7/Dockerfile, packages/mariadb-10.8-mroonga/yum/almalinux-8/Dockerfile, packages/mariadb-10.8-mroonga/yum/centos-7/Dockerfile
=> packages mariadb: add support for the latest mariadb 10.7 and 10.8

packages/Rakefile, packages/mariadb-10.10-mroonga/Rakefile, packages/mariadb-10.11-mroonga/Rakefile, packages/mariadb-10.4-mroonga/Rakefile, packages/mariadb-10.5-mroonga/Rakefile, packages/mariadb-10.6-mroonga/Rakefile, packages/mariadb-10.7-mroonga/Rakefile, packages/mariadb-10.8-mroonga/Rakefile, packages/mariadb-10.9-mroonga/Rakefile, packages/mroonga-package-task.rb, packages/mysql-8.0-mroonga/Rakefile, packages/mysql-community-5.7-mroonga/Rakefile, packages/mysql-community-8.0-mroonga/Rakefile, packages/mysql-community-minimal-8.0-mroonga/Rakefile, packages/percona-server-5.7-mroonga/Rakefile, packages/percona-server-8.0-mroonga/Rakefile, packages/source/Rakefile
Usage:
```console
$ cd mroonga/packages
$ rake source
```
---
Create files by this script.
```
└── source
├── repositories
│   └── source
│       └── mroonga
│           ├── mroonga-13.05.tar.gz
│           ├── mroonga-13.05.tar.gz.asc
│           └── mroonga-latest.tar.gz -> mroonga-13.05.tar.gz
└── tmp
└── downloads
└── 13.05
└── mroonga-13.05.tar.gz
```
Create .htaccess as below by this script.
```
Redirect /source/mroonga/mroonga-13.05.tar.gz https://github.com/mroonga/mroonga/releases/download/v13.05/mroonga-13.05.tar.gz
Redirect /source/mroonga/mroonga-13.05.tar.gz.asc https://github.com/mroonga/mroonga/releases/download/v13.05/mroonga-13.05.tar.gz.asc
Redirect /source/mroonga/mroonga-latest.tar.gz https://github.com/mroonga/mroonga/releases/download/v13.05/mroonga-13.05.tar.gz …
```
=> packages source: stop uploading to packages.groonga.org

.github/workflows/windows.yml
Because we have already released groonga-normalizer-mysql 1.2.3.
=> ci windows: remove needless expression

packages/mysql-8.0-mroonga/debian/changelog
* https://launchpad.net/~groonga/+archive/ubuntu/ppa/+sourcepub/15799241/+listing-archive-extra
* https://launchpad.net/~groonga/+archive/ubuntu/ppa/+sourcepub/15799242/+listing-archive-extra
=> Rebuilt against MySQL 8.0.35

packages/mysql-8.0-mroonga/debian/changelog
https://github.com/mroonga/mroonga/pull/670#discussion_r1494011798
=> package mysql-8.0: fix MySQL version

ha_mroonga.cpp, ha_mroonga.hpp, mrn_mysql_compat.h
Fix #679.
See: https://github.com/MariaDB/server/commit/22b3ba93121581db1cca4d2f9bfaf8d889cb2b32
However, I think that this implement is complex.
So, this implement is not good probably...
Could you any good advice to me?
=> mariadb: follow enable_indexes() and disable_indexes() API change

.github/workflows/linux.yml, packages/yum/test.sh
GitHub: fix GH-684
ref: https://discuss.linuxcontainers.org/t/network-issue-with-almalinux-8-9-on-github-actions-using-incus/20046/6?u=otegami
=> ci: add 10-second sleep delay to stabilize the network setting on AlmaLinux

.github/workflows/linux.yml
ref: https://github.com/groonga/groonga/pull/1789
=> ci linux: add Apache Arrow source

packages/mysql-community-8.4-mroonga/debian/changelog, packages/mysql-community-8.4-mroonga/yum/mysql-community-8.4-mroonga.spec.in
=> packages mysql-community-8.4: use the latest MySQL Community Server

packages/mysql-community-8.0-mroonga/debian/changelog, packages/mysql-community-8.0-mroonga/yum/mysql-community-8.0-mroonga.spec.in
=> packages mysql-community-8.0: use the latest MySQL Community Server

doc/locale/ja/LC_MESSAGES/contribution/documentation.po, doc/source/contribution/documentation.md
ref: https://github.com/mroonga/mroonga/issues/707
=> doc contribution/documentation: add how to install tools to required software section

.github/workflows/linux.yml, packages/mysql-community-8.0-mroonga/apt/ubuntu-noble/Dockerfile, packages/mysql-community-8.4-mroonga/apt/ubuntu-noble/Dockerfile
=> ci mysql-community-8.*: enable Ubuntu 24.04

doc/files.am, doc/files.cmake, doc/locale/ja/LC_MESSAGES/install/centos.po, doc/source/install/centos.md
=> doc install/centos: restore CentOS page for existed links

packages/mariadb-11.4-mroonga/yum/mariadb-11.4-mroonga.spec.in
PR for `add-support-for-mariadb-11.4-almalinux-8` branch.
=> packages: Build with CMake

.github/workflows/linux.yml, packages/mariadb-11.4-mroonga/Rakefile, packages/mariadb-11.4-mroonga/yum/almalinux-9/Dockerfile
=> packages mariadb: add support for mariadb 11.4 for AlmaLinux 9

packages/mysql-community-8.4-mroonga/yum/almalinux-8/Dockerfile, packages/mysql-community-8.4-mroonga/yum/almalinux-9/Dockerfile, packages/mysql-community-8.4-mroonga/yum/mysql-community-8.4-mroonga.spec.in
=> packages yum mysql-community-8.4-mroonga: simplify

doc/locale/ja/LC_MESSAGES/developer/release.po
Update `.po` as we missed updating `.po` when we updated `.rst`.
=> docs ja: Update `developer/release.po`

doc/locale/ja/LC_MESSAGES/install/windows.po, doc/source/install/windows.rst
GitHub: fix GH-827
Add this command as it is required for setup.
Reported by aki360P. Thanks!!!
=> docs: Add `mariadb-install-db` execution to the installation steps on Windows

.github/workflows/linux.yml, packages/Rakefile, packages/mysql-community-minimal-8.4-mroonga/Rakefile, packages/mysql-community-minimal-8.4-mroonga/yum/almalinux-9/Dockerfile, packages/mysql-community-minimal-8.4-mroonga/yum/mysql-community-minimal-8.4-mroonga.spec.in, packages/yum/test.sh
=> packages mysql-community-minimal-8.4: add

.github/workflows/linux.yml, setup.sh
You can use this to setup development environment for Mroonga.
=> ci: add setup script

.github/workflows/linux.yml, Makefile.am
This is deployed to mroonga.org on release.
=> ci: add support for releasing documents

doc/locale/ja/LC_MESSAGES/install/ubuntu.po, doc/source/install/ubuntu.rst
We has already supported Noble.
=> docs install/ubuntu: update supported versions

.github/workflows/linux.yml, packages/Rakefile, packages/mroonga-package-task.rb, packages/percona-server-8.4-mroonga/Rakefile, packages/percona-server-8.4-mroonga/yum/almalinux-9/Dockerfile, packages/percona-server-8.4-mroonga/yum/percona-server-8.4-mroonga.spec.in, packages/yum/test.sh
=> packages percona-server: add support for Percona Server 8.4

doc/source/developer/debug.md
=> docs debug: update MariaDB version

doc/locale/ja/LC_MESSAGES/news/15.po, doc/source/news/15.md
=> doc: add 15.09 entry

doc/locale/ja/LC_MESSAGES/news/15.po, doc/source/news/15.md
=> docs: Fix MariaDB typo

doc/locale/ja/LC_MESSAGES/news/15.po, doc/source/news/15.md
=> doc news: update release version and date about v15.10 

.github/workflows/mariadb.yml
* Improve matrix id
* https://github.com/mroonga/mroonga/pull/948#discussion_r2206013028
* Check out `${{ github.repository }}`
* Useful for checking in fork repository
=> ci: mariadb: improve settings

.github/workflows/mariadb.yml
=> ci: mariadb: fix the run condition

doc/locale/ja/LC_MESSAGES/tutorial/wrapper.po, doc/source/tutorial/wrapper.rst
https://mroonga.org/docs/news/12.html#release-12-02
=> docs wrapper mode: add note that dropped support for MySQL 8.0 or later

doc/locale/ja/LC_MESSAGES/install/almalinux.po, doc/source/install/almalinux.rst
- Added the required Apache Arrow repository configuration
- Used code block for consistency
=> doc install: update AlmaLinux installation
